/* ARTVELCHIV — curated legal guidance, not a legal-clearance engine.
 * Every source has a defined scope. No source updates or filings are implied.
 * Shared by the interface and both language-model providers. No private data here.
 */
export const REVIEWED='2026-10-04';
const source=(id,title,url,scope,rule)=>({id,title,url,scope,rule,reviewed:REVIEWED,kind:id==='cinoa-ethics'?'professional-code':'official-source',reviewAfterDays:30});
export const SOURCES=[
 source("ca-export","Canada · guide de l’exportation des biens culturels","https://www.canada.ca/en/canadian-heritage/services/export-permits-cultural-property/guide-exporting.html","Sortie du Canada","Appliquer les critères cumulés de la Liste de contrôle à la catégorie : âge, auteur décédé lorsque pertinent et seuils particuliers. Distinguer permis temporaire, permanent et général ; la demande relève d’un résident canadien et les autres restrictions demeurent. Ne pas transformer un seul seuil d’âge en autorisation."),
 source("jp-export","Japon · Agency for Cultural Affairs","https://www.bunka.go.jp/english/policy/cultural_properties/international/","Sortie du Japon","Les catégories désignées, notamment trésors nationaux et biens culturels importants, sont en principe interdites d’exportation, sous réserve des exceptions. Pour les objets d’art ancien, examiner le certificat attestant l’absence de désignation, Kobijutsuhin yushutsu kansa shomei, auprès de l’Agence ; ne pas le confondre avec une expertise d’authenticité."),
 source("au-export","Australie · Office for the Arts, exportation","https://www.arts.gov.au/what-we-do/cultural-heritage/movable-cultural-heritage/exporting-cultural-property-australia","Sortie d’Australie","Rapprocher l’objet de la National Cultural Heritage Control List et du registre des refus. Le régime distingue objets protégés de classes A/B, permis, interdictions et exemptions. Certains prêts entrants exigent une exemption avant arrivée pour préparer la réexportation ; les procédures peuvent prendre plusieurs mois."),

 source("uk-export","Royaume-Uni · exportation des biens culturels","https://www.gov.uk/guidance/export-art-antiques-and-cultural-goods-special-rules","Départ de Grande-Bretagne ou d’Irlande du Nord","Arts Council England administre les licences. Déterminer la localisation exacte : les procédures diffèrent entre Grande-Bretagne et Irlande du Nord. Vérifier catégorie, seuils et licence générale avant de choisir la demande ; conserver la licence délivrée avec la déclaration douanière. Une licence britannique ne vaut pas licence de sortie d’un État membre de l’UE."),
 source("uk-aml","Royaume-Uni · HMRC, art market participants","https://www.gov.uk/guidance/money-laundering-supervision-for-art-market-participants","Professionnels relevant des Money Laundering Regulations britanniques","L’activité professionnelle de commerce ou d’intermédiation sur des œuvres, pour une transaction ou des opérations liées d’au moins 10 000 euros, peut imposer enregistrement et vigilance HMRC. Examiner la définition fiscale d’œuvre, le rôle réel et les exceptions ; ne pas confondre simple conseil et intermédiation active."),
 source("ch-customs","Suisse · OFC, importation, transit et exportation","https://www.bak.admin.ch/en/import-transit-and-export-of-cultural-property","Biens culturels au sens de la LTBC suisse","Les biens culturels doivent être déclarés comme tels à la douane, y compris pour le dépôt en entrepôt. La révision de l’ordonnance entrée en vigueur le 1er janvier 2026 ajoute notamment datation et dimensions aux informations de déclaration. Examiner les accords bilatéraux et les restrictions applicables avant de conclure sur l’admission."),
 source("ch-trade","Suisse · OFC, commerce d’art et ventes aux enchères","https://www.bak.admin.ch/en/informations-for-the-art-trade","Professionnels concernés par la LTBC en Suisse","Documenter l’identité du cédant et son pouvoir de disposition ; obtenir sa déclaration écrite sur ce pouvoir. Rapprocher provenance, acquisition et obligations de diligence du guide OFC en vigueur. Une déclaration du vendeur ne remplace pas les autres vérifications."),
 source("us-import","États-Unis · CBP, objets d’art et antiquités","https://www.help.cbp.gov/s/article/Article1143?language=en_US","Importation aux États-Unis ; classement tarifaire et licéité distincts","Documenter âge, catégorie, valeur et origine pour le classement douanier. Examiner séparément les restrictions culturelles et les accords applicables, notamment sous 19 CFR 12.104g. Un classement tarifaire favorable ne démontre ni exportation licite ni droit d’importer. Ne pas promettre une absence totale de droits, taxes ou frais sur cette seule fiche."),
 source("hk-declaration","Hong Kong · déclaration d’importation et d’exportation","https://www.customs.gov.hk/en/service-enforcement-information/cargo-clearance/import-export-declaration/","Importations et exportations à Hong Kong, hors marchandises exemptées","Une déclaration exacte et complète est en principe requise dans les 14 jours suivant l’importation ou l’exportation, sous réserve des exemptions. Préparer facture, manifeste et description avec le transporteur. Ce délai déclaratif ne remplace pas les autorisations éventuellement exigées avant mouvement."),
 source("hk-customs","Hong Kong · contrôle des marchandises","https://www.customs.gov.hk/en/service-enforcement-information/cargo-clearance/","Territoire douanier de Hong Kong","Le régime de port franc n’efface pas les contrôles douaniers, déclarations ni restrictions. Ne pas transposer les règles de Chine continentale à Hong Kong ; examiner séparément la sortie du pays précédent, notamment si le bien vient de Chine continentale, et les composants protégés."),
 source("it-export","Italie · ministère de la Culture, plateforme SUE","https://sue.cultura.gov.it/","Sortie ou entrée de biens culturels en Italie","SUE traite notamment ALC, LED, sorties temporaires, déclarations et certificats d’entrée CAS/CAI. Le portail distingue depuis mai 2026 les circuits des biens artistiques et ceux des livres/archives et leurs déclarations de valeur. Identifier la catégorie et le bureau compétent ; ne pas appliquer un seuil unique à tous les objets ni confondre ancienneté de l’œuvre et durée des droits d’auteur."),
 source("de-export","Allemagne · guide des autorisations KGSG","https://www.kulturgutschutz-deutschland.de/SharedDocs/Downloads/DE/Merkblaetter/Flowchart.html?nn=124576","Sortie d’Allemagne","La procédure dépend de la protection nationale, de la destination, de la catégorie, de l’âge et de la valeur. Utiliser le parcours officiel de détermination de l’autorisation ; les règles européennes ne remplacent pas le KGSG national."),
 source("cinoa-ethics","CINOA · code de déontologie et charte, 2024","https://www.cinoa.org/about/code-of-ethics/","Code professionnel ; portée selon adhésion et engagements, pas loi universelle","Documenter la provenance et le titre, proportionner les diligences aux risques et donner une description exacte, y compris les réserves. Le code concerne les organisations membres et leurs membres selon leur cadre ; ses recommandations ne sont pas automatiquement des obligations légales de tout marchand."),
 source("fr-auction-ethics","France · recueil déontologique des ventes volontaires, 2022","https://www.legifrance.gouv.fr/jorf/id/JORFARTI000045522972","Opérateurs et commissaires-priseurs de ventes volontaires français","Le recueil approuvé le 30 mars 2022 prévoit des diligences sur identification, authenticité, provenance, droits du vendeur et composants réglementés. Ne pas dissimuler les doutes ; en cas de doute sur l’origine illicite, examiner abstention et information des autorités selon les textes. Ne pas transposer ce statut à toute galerie."),

 source('eu-customs-procedures','UE · régimes particuliers et carnet ATA','https://www.douane.gouv.fr/dossier/les-regimes-particuliers','Biens non Union sous régime particulier','L’admission temporaire et l’entrepôt permettent certains usages ou stockages en suspension de droits et taxes. Les conditions de vente, mise en libre pratique, réexportation et délais dépendent du régime et de l’autorisation. Lire la déclaration et consulter le représentant en douane avant livraison.'),
 source('eu-import','UE · règlement 2019/880 et mise en œuvre 2021/1079','https://www.douane.gouv.fr/demarche/importer-des-biens-culturels','Entrée dans le territoire douanier de l’Union de biens créés ou découverts hors UE','L’introduction de biens culturels illicitement exportés est interdite. Depuis le 28 juin 2025, les parties B et C imposent respectivement une licence ou une déclaration ICG. Les exceptions et le pays dont il faut prouver la sortie licite nécessitent l’historique du bien. L’article L111-8 du code du patrimoine a ses propres conditions cumulatives ; pas de permis d’origine universel.'),
 source('eu-thresholds','UE · catégories et seuils des formalités ICG','https://www.douane.gouv.fr/sites/default/files/2023-05/17/biens-culturels-reglementation-europeenne-applicable-a-l-introduction-et-a-l-importation.pdf','Biens entrant dans les catégories précises de l’annexe 2019/880','Partie B : biens archéologiques et éléments de monuments démembrés de plus de 250 ans, sans seuil de valeur. Partie C : catégories visées de plus de 200 ans, valeur d’au moins 18 000 € par objet. Âge, catégorie et valeur sont cumulatifs en C. Une sculpture ancienne n’est pas nécessairement archéologique. Ne jamais déduire une exemption générale de l’absence de formalité ICG.'),
 source('monaco-customs','Monaco · territoire douanier (CDU, article 4)','https://www.douane.gouv.fr/sites/default/files/2024-03/01/Manuel-transit-preuve-du-statut-p77-a-183.pdf','Circulation vers ou depuis Monaco','Monaco appartient au territoire douanier de l’Union en vertu de la convention douanière franco-monégasque. Ce n’est pas un État membre de l’UE. Cette inclusion ne rend pas automatiquement applicables toutes les règles civiles, fiscales, de consommation ou de propriété intellectuelle françaises.'),
 source('india-export','Inde · Antiquities and Art Treasures Act 1972, sections 2–3','https://www.wipo.int/wipolex/en/legislation/details/14946','Sortie physique d’Inde','Les antiquités visées comprennent notamment les objets ayant au moins 100 ans et certains manuscrits ou documents ayant au moins 75 ans. Les art treasures sont désignés par notification. Leur exportation est réservée au gouvernement central ou à une autorité/agence autorisée : ce n’est pas un permis ordinaire ouvert à tout vendeur. Faire confirmer la catégorie par l’ASI et les douanes avant expédition. Une origine stylistique indienne ne prouve pas une sortie actuelle d’Inde.'),
 source('fr-export','France · exportation des biens culturels','https://www.douane.gouv.fr/demarche/exporter-des-biens-culturels','Sortie de France ou du territoire douanier de l’Union','Distinguer certificat national / autorisation de sortie temporaire et licence européenne d’exportation (règlement 116/2009). Les seuils varient par catégorie, ancienneté et valeur ; ne pas réutiliser les seuils ICG d’importation. Les trésors nationaux relèvent d’une sortie temporaire. Examiner la durée de présence en France et le régime temporaire avant de conclure.'),
 source('cites','Espèces protégées · CITES et règlement 338/97','https://www.douane.gouv.fr/demarche/importer-des-specimens-cites','Objets comprenant des espèces animales ou végétales réglementées','Les documents dépendent de l’espèce, de l’annexe, du trajet, de la date et du régime. L’ancienneté ne dispense pas automatiquement de permis ou de certificat. Identifier les composants ; examiner les permis d’exportation/réexportation et d’importation avant transport. En France, service CITES compétent, généralement DREAL/DRIEAT/DEAL.'),
 source('fr-attribution','France · décret 81-255, articles 1 à 8','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000684875/','Descriptions et vente d’œuvres ou objets de collection en France','Le nom de l’artiste, la datation et les expressions d’attribution ont des effets distincts. « Attribué à » n’équivaut pas à une œuvre garantie de la main de l’artiste ; « d’après » doit rester distinct. Décrire les reproductions et les parties postérieures. Rapprocher les affirmations du catalogue, du certificat et de la facture avant de rédiger le contrat.'),
 source('fr-copyright','France · CPI L123-1 (durée des droits patrimoniaux)','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006278937','Durée ordinaire de protection en France','La règle ordinaire couvre la vie de l’auteur puis l’année du décès et les 70 années suivantes. Le repère de fin est le 31 décembre de l’année du décès + 70, sous réserve des régimes spéciaux et internationaux. L’âge de l’objet n’est pas la date de décès de l’artiste. Une notice biographique ne vaut pas autorisation d’utilisation.'),
 source('fr-rights','France · CPI L111-3 et L121-1','https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006069414/LEGISCTA000006133323/','Propriété matérielle, reproduction et droit moral','Acheter l’objet ne transfère pas automatiquement les droits d’auteur. Le droit moral reste protégé en France indépendamment de l’expiration des droits patrimoniaux. Examiner séparément vente matérielle, publication des images et autorisations ; ne pas appeler une œuvre « libre de tous droits » sur la seule base d’une date.'),
 source('fr-resale','France · CPI L122-8, droit de suite','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033688066','Reventes d’originaux avec intervention d’un professionnel en France','Le droit de suite dépend notamment de l’originalité/édition, de l’auteur et de ses ayants droit, de la revente, du professionnel et des conditions territoriales et financières. Une date de décès ne suffit pas à qualifier toute la vente. Identifier le bénéficiaire et l’organisme compétent avant de calculer ou d’attribuer des frais.'),
 source('mc-resale','Monaco · loi 1.526 du 1er juillet 2022','https://journaldemonaco.gouv.mc/Journaux/2022/Journal-8599/Loi-n-1.526-du-1er-juillet-2022-relative-au-droit-de-suite','Droit de suite monégasque','Monaco dispose d’un régime propre de droit de suite. Ne pas appliquer automatiquement les modalités françaises ; vérifier les conditions et le texte d’application monégasque pour la transaction.'),
 source('fr-aml','France · vigilance des marchands d’art et d’antiquités','https://www.douane.gouv.fr/fiche/marchands-dart-et-dantiquites','Professionnels assujettis en France','Le secteur est assujetti à la lutte contre le blanchiment pour les transactions ou séries liées d’au moins 10 000 €. Identifier client, représentation et bénéficiaire effectif, apprécier le risque et conserver les justificatifs selon le cadre applicable. Ne pas conclure qu’un montant inférieur exclut tout contrôle. Les vérifications internes ne sont pas des annexes publiques du dossier acheteur.'),
 source('mc-aml','Monaco · loi 1.362 et ordonnance 2.318','https://legimonaco.mc/tnc/loi/2009/08-03-1.362','Professionnels assujettis à Monaco','Le régime monégasque de vigilance doit être examiné selon la catégorie de professionnel et l’opération. Ne pas transposer les seuils français ni confondre art et autres objets de valeur. Vérifier la loi et son ordonnance d’application auprès du dispositif monégasque compétent avant de conclure.'),
 source('mc-patrimoine','Monaco · loi 1.446 sur le patrimoine national','https://legimonaco.mc/tnc/loi/2017/06-12-1.446/','Protection patrimoniale à Monaco','Examiner la protection patrimoniale locale et les éventuelles restrictions avant une sortie. L’union douanière n’écarte pas les règles monégasques du patrimoine. Ce repère ne permet pas, seul, de calculer les autorisations requises.'),
 source('fr-vat','France · BOI-TVA-SECT-90-40, version du 14 mai 2025','https://bofip.impots.gouv.fr/bofip/1285-PGP.html/identifiant=BOI-TVA-SECT-90-40-20250514','TVA française des œuvres d’art, objets de collection et antiquités fiscalement qualifiés','Depuis le 1er janvier 2025, les livraisons qualifiées relèvent du taux réduit de 5,5 %, sauf application du régime de la marge. Le régime dépend de l’acquisition, du vendeur et de l’opération. Ne pas présumer la TVA ni étendre le taux à tout objet de valeur. Importation, livraison et marge doivent rester distinctes.'),
 source('fr-vat-margin','France · BOI-TVA-SECT-90-20-20','https://bofip.impots.gouv.fr/bofip/13268-PGP.html/identifiant=BOI-TVA-SECT-90-20-20-20250514','Assujettis-revendeurs et régime de la marge','Examiner la facture d’achat et la qualité du cédant avant de proposer le régime de la marge. Ne pas cumuler automatiquement marge et taux réduit de 5,5 %. Une facture ne prouve pas à elle seule l’acquittement de TVA d’importation.'),
 source('fr-consumer','France · Code de la consommation, L221-18','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032226842','Contrats à distance ou hors établissement avec un consommateur lorsque le droit français s’applique','Le délai de rétractation de principe est de 14 jours, sous réserve du champ du texte et des exceptions. Les ventes aux enchères publiques et les ventes en ligne ne sont pas assimilables sans examen. Prévoir informations précontractuelles, garanties et modalités de retour selon le contrat ; ne pas supprimer des droits impératifs.'),
 source('fr-registry','France · Code pénal, article 321-7','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000023717783','Professionnels concernés par le registre des objets mobiliers','Certaines activités de vente de biens mobiliers usagés ou acquis hors fabrication/commerce imposent un registre. Conserver identification, provenance et vendeur. Une archive Artvelchiv n’est pas automatiquement un registre réglementaire conforme.'),
 source('fr-sale','France · Code civil, vente et garanties','https://www.legifrance.gouv.fr/codes/id/LEGITEXT000006070721','Vente soumise au droit français','Examiner information et consentement, délivrance, garantie d’éviction (1626) et vices cachés (1641). Définir objet/attribution, parties et mandat, prix et fiscalité, paiement, livraison, assurance et réserves. Les garanties impératives et règles de conflit ne peuvent être écartées par une simple clause modèle.'),
 source('restricted-origin','UE · biens culturels irakiens et syriens','https://www.douane.gouv.fr/demarche/importer-des-biens-culturels','Provenance irakienne ou syrienne','Des restrictions spécifiques s’ajoutent au régime général. Reconstituer les dates et circonstances de sortie et consulter les règlements 1210/2003 (Irak) et 36/2012 modifié notamment par 1332/2013 (Syrie). Ne pas conclure à une circulation autorisée sans examen des justificatifs et exceptions.')
];
const get=id=>SOURCES.find(s=>s.id===id);
const norm=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const EU=['france','allemagne','autriche','belgique','bulgarie','chypre','croatie','danemark','espagne','estonie','finlande','grece','hongrie','irlande','italie','lettonie','lituanie','luxembourg','malte','pays-bas','pologne','portugal','republique tcheque','tchequie','roumanie','slovaquie','slovenie','suede'];
export const isEU=x=>EU.includes(norm(x));
export const isCustomsUnion=x=>isEU(x)||norm(x)==='monaco';
const tr=(lang,fr,en)=>lang==='en'?en:fr;
export function artistTerm(record,year=new Date().getFullYear()){
 const values=[...new Set((record.artistReference?.death||[]).map(String).filter(x=>/^\d{4}$/.test(x)).map(Number))];
 if(values.length!==1||values[0]>year||values[0]<1)return null;
 const death=values[0];return {death,ordinaryEndYear:death+70,ordinaryExpired:year>death+70,scope:'France',clearance:false};
}
export function documentsFor(r,lang='fr'){
 const out=[{id:'acquisition',title:tr(lang,'Facture ou bordereau d’achat','Purchase invoice or auction receipt'),why:tr(lang,'Pour retrouver l’acquisition, le vendeur et la description d’origine.','To recover the acquisition details, seller and original description.')},{id:'identity',title:tr(lang,'Certificat, expertise ou ancien catalogue','Certificate, expert opinion or previous catalogue'),why:tr(lang,'Pour préciser l’artiste, la date et les matériaux.','To establish the recorded attribution, date and materials.')}];
 if(r.lieu&&r.dest&&r.lieu!==r.dest||r.arrivee==='importee'||r.douaneDocument)out.push({id:'transport',title:tr(lang,'Documents de transport ou de douane','Shipping or customs documents'),why:tr(lang,'Pour lire le trajet, le régime déclaré et les éventuelles échéances.','To identify the route, declared procedure and any deadlines.')});
 if(r.role==='mandataire')out.push({id:'mandate',title:tr(lang,'Mandat du propriétaire','Owner’s mandate'),why:tr(lang,'Pour préciser qui peut vendre et signer.','To establish authority to sell and sign.')});
 if(r.protege==='oui'||r.protege==='inconnu'||/ivoire|ivory|corail|coral|ecaille|tortoise/i.test(norm(r.materiauxDetail)))out.push({id:'materials',title:tr(lang,'Justificatif des matériaux','Material identification or permit'),why:tr(lang,'Pour examiner les composants réglementés.','To assess regulated components.')});
 return out;
}
function originalPlan(r={},lang='fr',year=new Date().getFullYear()){
 const items=[];const add=(id,fr,en,detailFR,detailEN,refs,priority=2)=>items.push({id,title:tr(lang,fr,en),detail:tr(lang,detailFR,detailEN),sources:refs.map(get).filter(Boolean),priority,status:'to-review'});
 const from=norm(r.lieu),to=norm(r.dest),creation=norm(r.creation),sale=['vente','achat'].includes(r.operation),archive=r.operation==='archiver';
 const moving=!!(from&&to&&from!==to&&!archive),incoming=moving&&!isCustomsUnion(from)&&isCustomsUnion(to),age=Number.isFinite(Number(r.annee))&&r.annee!==''&&r.annee!=null?year-Number(r.annee):null;
 if(moving&&from==='inde')add('india','Vérifier la sortie d’Inde avant le transport','Check export eligibility before shipping from India',age!==null&&age>=100?'Cette datation place l’objet dans une tranche d’âge susceptible de relever de l’interdiction d’exportation des antiquités. Demandez une confirmation de classement à l’ASI avec la facture, les photos et la datation ; une licence ordinaire ne suffit pas.':'La sortie dépend de l’âge, de la catégorie et d’un éventuel classement. Joignez facture, photos et datation : il faut d’abord écarter les restrictions indiennes, avant d’organiser le transport.',age!==null&&age>=100?'This date puts the object within an age range potentially covered by India’s antiquities export prohibition. Ask the ASI to confirm its classification using the invoice, photographs and dating evidence; an ordinary export permit is not sufficient.':'Export depends on age, category and any protected designation. Supply the invoice, photographs and dating evidence so Indian restrictions can be checked before shipping.',['india-export'],0);
 if(incoming){
  add('import','Préparer l’entrée à destination','Prepare the import at destination',to==='monaco'?'Monaco fait partie du territoire douanier de l’Union. Réunissez facture, provenance et justificatifs de sortie licite ; nous distinguons ensuite les documents culturels du dédouanement.':'Réunissez facture, provenance et justificatifs de sortie licite. Les formalités culturelles et la déclaration douanière sont deux vérifications distinctes.',to==='monaco'?'Monaco is within the EU customs territory. Gather the invoice, provenance and lawful-export evidence; cultural-goods requirements are assessed separately from customs clearance.':'Gather the invoice, provenance and lawful-export evidence. Cultural-goods requirements and the customs declaration are separate checks.',['eu-import',...(to==='monaco'?['monaco-customs']:[])],1);
  if(!isEU(creation))add('icg','Identifier le document culturel requis','Identify the cultural-goods document required',age!==null&&age>200&&Number(r.valeur)>=18000?'L’âge et la valeur appellent un examen ICG : déclaration pour les catégories de la partie C ; licence pour les biens archéologiques ou éléments de monuments de la partie B de plus de 250 ans. Il reste à établir la catégorie et le pays de création ou découverte.':'La catégorie, la datation, la valeur et le pays de création ou découverte permettent de déterminer s’il faut une licence ou une déclaration ICG. Même sans formalité ICG, la sortie licite reste à documenter.',age!==null&&age>200&&Number(r.valeur)>=18000?'The age and value require an ICG assessment: an importer statement for Annex C categories; a licence for Annex B archaeological objects or monument elements over 250 years old. Category and country of creation or discovery still need evidence.':'Category, date, value and country of creation or discovery determine whether an ICG licence or importer statement is needed. Lawful export still matters where no ICG document is required.',['eu-thresholds'],1);
 }
 if(moving&&from==='france')add('export','Vérifier les autorisations de sortie','Check export and removal requirements','La catégorie, la datation, la valeur et la durée de présence en France déterminent les documents de sortie à examiner. Ajoutez la facture et les anciennes autorisations.','Category, date, value and time in France determine which removal and export documents need assessment. Add the invoice and any previous permits.',['fr-export'],1);
 if(!archive&&isCustomsUnion(from)&&(r.douaneDocument||r.arrivee==='importee'))add('customs','Lire le régime indiqué sur vos documents','Read the procedure recorded in your documents','Un carnet ATA, une admission temporaire ou un entrepôt peut imposer des conditions avant vente ou remise. Joignez le document ; une facture seule ne prouve pas la libre pratique.','An ATA carnet, temporary admission or customs warehousing may restrict sale or delivery. Add the document; a purchase invoice alone does not establish free circulation.',['eu-customs-procedures'],1);
 if(r.protege==='oui'||r.protege==='inconnu'||/ivoire|ivory|corail|coral|ecaille|tortoise/.test(norm(r.materiauxDetail)))add('cites','Préciser le composant protégé','Identify the protected material','Une photo rapprochée et un justificatif du matériau permettront d’examiner les permis CITES. L’ancienneté de l’objet ne suffit pas à l’en dispenser.','A close-up and material identification will help assess CITES documents. Age alone does not establish an exemption.',['cites'],1);
 if(/irak|iraq|syrie|syria/.test([from,creation,norm(r.origineCulturelle),norm(r.provenanceTexte)].join(' ')))add('origin','Reconstituer les sorties du pays d’origine','Reconstruct the export history','Cette provenance appelle un examen spécifique des restrictions et des dates de sortie. Conservez tous les anciens titres et documents de transport avant toute circulation ou vente.','This provenance requires specific checks on restrictions and export dates. Gather previous ownership and shipping records before sale or movement.',['restricted-origin'],0);
 if(sale){add('sale','Préparer une description qui engage justement','Get the sale description right','Nous rapprochons facture, certificat et catalogue pour reprendre la bonne attribution, les matériaux, la datation et les réserves dans les documents de vente. Les règles françaises ci-dessous ne sont applicables qu’après confirmation du droit de la vente.','We compare the invoice, certificate and catalogue to carry the supported attribution, materials, date and qualifications into the sale documents. The French rules below apply only where the sale is governed by them.',['fr-attribution','fr-sale'],3);
  add('parties','Identifier les parties, discrètement','Identify the parties, discreetly','Le mandat et les informations sur le vendeur et l’acheteur servent aux vérifications internes. La confidentialité côté acheteur n’efface pas les obligations d’identification ou de communication nécessaires. Le lieu d’établissement du professionnel détermine le régime de vigilance.','The mandate and party details support private checks. Buyer-facing privacy does not remove required identification or disclosure. The professional’s place of establishment determines the applicable due-diligence regime.',['fr-aml','mc-aml'],4);
  add('tax','Retenir la bonne fiscalité à partir de l’achat','Use the purchase history to establish tax treatment','Ajoutez la facture d’acquisition. Le régime dépend notamment du vendeur, du pays et du mode d’acquisition ; un objet de valeur n’est pas automatiquement une œuvre d’art au sens fiscal.','Add the acquisition invoice. Treatment depends on the seller, jurisdiction and acquisition route; not every valuable object qualifies as an artwork for tax purposes.',['fr-vat','fr-vat-margin'],4);
  if(r.acheteur==='particulier'&&r.mode==='distance')add('consumer','Préparer les informations de l’acheteur','Prepare the buyer’s terms','La vente à distance à un particulier appelle un examen de l’information préalable, de la rétractation et des garanties selon le droit applicable. Nous avons besoin des pays des parties et du mode exact de vente.','A distance sale to a private buyer requires assessment of pre-contract information, withdrawal and warranties under the applicable law. The parties’ countries and precise sales process are needed.',['fr-consumer'],3);
 }
 if(r.artisteNom){const t=artistTerm(r,year);add('rights','Distinguer la vente de l’œuvre et ses images','Separate ownership of the work from image rights',t?`La notice associée indique un décès en ${t.death}. Le repère ordinaire français est le 31 décembre ${t.ordinaryEndYear}. Il ne vaut pas autorisation : attribution, régimes particuliers, publication des images et éventuel droit de suite restent à examiner.`:'Nous recherchons les repères de l’artiste. Inutile de connaître vous-même la durée des droits : confirmez la bonne personne et joignez les éventuelles autorisations d’images.',t?`The linked record gives ${t.death} as the death year. The ordinary French term points to 31 December ${t.ordinaryEndYear}. This is not clearance: attribution, exceptions, image use and any resale royalty still need assessment.`:'We look up the artist’s biographical details. You do not need to calculate the copyright term: confirm the right person and add any image permissions.',['fr-copyright','fr-rights',...(sale?['fr-resale',...(from==='monaco'||to==='monaco'?['mc-resale']:[])]:[])],3);}
 const routes={
 "australie":{"export": ["au-export"], "import": [], "fr": "Vérifier le contrôle australien avant le départ", "en": "Check Australian export controls before departure", "detailFR": "La liste de contrôle et les éventuelles mesures de protection déterminent la procédure. Joignez facture, provenance et datation avant de fixer l’expédition.", "detailEN": "The Control List and any protective measures determine the procedure. Add the invoice, provenance and dating evidence before arranging shipment."},
 "japon":{"export": ["jp-export"], "import": [], "fr": "Vérifier la désignation patrimoniale japonaise", "en": "Check Japanese cultural-property designation", "detailFR": "Joignez photos, description et justificatifs de provenance. Pour l’art ancien, examinons le certificat de non-désignation auprès de l’Agence pour les affaires culturelles avant le départ.", "detailEN": "Add photographs, a description and provenance records. For antique art, assess the certificate of non-designation with the Agency for Cultural Affairs before departure."},
 "canada":{"export": ["ca-export"], "import": [], "fr": "Préparer le permis de sortie canadien", "en": "Prepare the Canadian export permit", "detailFR": "La catégorie, la datation, l’auteur et la valeur permettent de consulter la Liste de contrôle. Joignez facture et catalogue ; le permis doit être demandé par un résident canadien.", "detailEN": "Category, date, artist and value determine the Control List assessment. Add the invoice and catalogue; a Canadian resident must apply for the permit."},
 'royaume-uni':{export:['uk-export'],import:[],fr:'Distinguer Grande-Bretagne et Irlande du Nord',en:'Distinguish Great Britain from Northern Ireland',detailFR:'Confirmez la localisation exacte et joignez facture, datation et anciennes licences. Nous orientons la préparation vers Arts Council England avant expédition.',detailEN:'Confirm the precise location and add the invoice, dating evidence and previous licences. This establishes the route to Arts Council England before shipment.'},
 'suisse':{export:['ch-customs'],import:['ch-customs'],fr:'Préparer la déclaration culturelle suisse',en:'Prepare the Swiss cultural-property declaration',detailFR:'Réunissez facture, provenance, datation et dimensions, puis les anciens documents douaniers. Le dépôt en entrepôt appelle aussi une déclaration ; les restrictions et accords bilatéraux restent à examiner.',detailEN:'Gather the invoice, provenance, date, dimensions and previous customs records. Warehousing also requires a declaration; restrictions and bilateral agreements need separate assessment.'},
 'etats-unis':{export:[],import:['us-import'],fr:'Documenter l’entrée aux États-Unis',en:'Document the US import',detailFR:'Joignez facture, provenance et preuve de sortie du pays d’origine. Le classement tarifaire et les restrictions sur les biens culturels doivent être examinés séparément avec le représentant en douane.',detailEN:'Add the invoice, provenance and evidence of lawful export from the source country. Tariff classification and cultural-property restrictions need separate assessment with the customs broker.'},
 'hong kong':{export:['hk-declaration','hk-customs'],import:['hk-declaration','hk-customs'],fr:'Préparer les documents pour Hong Kong',en:'Prepare the Hong Kong documents',detailFR:'Joignez facture et documents de transport. Le port franc conserve des obligations de déclaration et des contrôles ; la sortie du pays précédent et les matériaux protégés restent à vérifier.',detailEN:'Add the invoice and shipping records. Free-port status does not remove declarations or controls; export from the previous country and regulated materials still need checking.'},
 'italie':{export:['it-export'],import:[],fr:'Identifier le bon parcours de sortie italien',en:'Identify the right Italian export procedure',detailFR:'La catégorie, la datation et les documents d’entrée permettent de choisir la démarche SUE et le bureau compétent. Joignez les anciens certificats avec la facture.',detailEN:'Category, date and entry records determine the SUE procedure and competent office. Add previous certificates with the invoice.'},
 'allemagne':{export:['de-export'],import:[],fr:'Vérifier la sortie selon le KGSG allemand',en:'Assess export under the German KGSG',detailFR:'Réunissez datation, valeur, provenance et éventuels documents de protection. Le parcours officiel permet d’identifier l’autorisation adaptée à la destination.',detailEN:'Gather dating evidence, value, provenance and any protection records. The official process identifies the permit for the destination.'}
 };
 if(moving){const a=routes[from],b=routes[to];if(a?.export.length)add('local-export-guided',a.fr,a.en,a.detailFR,a.detailEN,a.export,1);if(b?.import.length)add('local-import-guided',b.fr,b.en,b.detailFR,b.detailEN,b.import,1);}
 if(sale)add('professional-care','Conserver les vérifications utiles','Keep a record of the relevant checks','Provenance, pouvoir de vendre et description étayée : nous regroupons les éléments utiles au dossier professionnel. Le code déontologique applicable dépend de votre activité et de vos affiliations.','Provenance, authority to sell and a supported description belong in the professional record. The applicable professional code depends on your activity and affiliations.',['cinoa-ethics',...((from==='france'||to==='france')?['fr-auction-ethics']:[]),...((from==='suisse'||to==='suisse')?['ch-trade']:[]),...((from==='royaume-uni'||to==='royaume-uni')?['uk-aml']:[])],4);
 if(moving&&!['france','inde','monaco'].includes(from)&&!routes[from]?.export.length)add('local-export','Vérifier aussi le droit du pays de départ','Check the departure country’s rules too','Les formalités locales de sortie ne sont pas encore qualifiées pour ce pays dans ce socle. Une confirmation des douanes ou de l’autorité du patrimoine est nécessaire avant d’annoncer une circulation autorisée.','This source pack does not yet establish the departure country’s export requirements. Customs or the cultural-heritage authority must confirm them before movement can be treated as authorised.',[],2);
 if(moving&&!isCustomsUnion(to)&&!routes[to]?.import.length)add('local-import','Confirmer les conditions à destination','Confirm the destination requirements','Le régime d’importation de cette destination reste à documenter auprès des autorités locales. Les seuils européens ne permettent pas de le déduire.','The destination’s import requirements still need local official verification. EU thresholds cannot establish them.',[],2);
 if(moving&&from==='monaco')add('mc-exit','Vérifier la protection patrimoniale locale','Check local heritage protection','Avant la sortie, examinez un éventuel classement ou une mesure de protection monégasque. Le régime douanier ne résout pas à lui seul cette question.','Before removal, check for any Monegasque designation or protection. Customs treatment alone does not answer this question.',['mc-patrimoine'],2);
 return {version:'guide-4.1',reviewed:REVIEWED,route:moving?`${r.lieu} → ${r.dest}`:'',items:items.sort((a,b)=>a.priority-b.priority),documents:documentsFor(r,lang),coverage:'Socle thématique France, Monaco et UE ; modules limités Inde, Royaume-Uni, Suisse, États-Unis, Hong Kong, Italie, Allemagne, Canada, Japon et Australie. Codes professionnels distingués des lois. Droit des contrats, fiscalité, sanctions et objets spécialisés non exhaustifs. Autres pays : qualification locale requise. Sources révisées manuellement, aucune veille automatique active.'};
}
function previousPromptContext(r,message=''){
 const p=plan(r);const ids=new Set(p.items.flatMap(x=>x.sources.map(s=>s.id)));
 // Topic matching selects trusted texts; message text is never inserted into instructions.
 const topic=norm(message);
 const countryTopics=[[/suisse|switzerland/,['ch-customs','ch-trade']],[/royaume.uni|united kingdom|britain|london|londres/,['uk-export','uk-aml']],[/etats.unis|united states|new york/,['us-import']],[/hong kong/,['hk-customs','hk-declaration']],[/italie|italy/,['it-export']],[/allemagne|germany/,['de-export']],[/canada/,['ca-export']],[/japon|japan/,['jp-export']],[/australie|australia/,['au-export']]];
 for(const [pattern,refs] of countryTopics)if(pattern.test(topic))refs.forEach(id=>ids.add(id));
 if(/deontolog|ethic|cinoa|provenance/.test(topic))ids.add('cinoa-ethics');
 if(/encher|auction/.test(topic)&&norm(r.lieu)==='france')ids.add('fr-auction-ethics');
 if(/inde|india/.test(topic))['india-export','eu-import','eu-thresholds','monaco-customs'].forEach(id=>ids.add(id));
 if(/import|export|douan|custom|transport/.test(topic))['eu-import','eu-thresholds','fr-export','monaco-customs','eu-customs-procedures'].forEach(id=>ids.add(id));
 if(/artiste|artist|deces|death|droit|copyright|70/.test(topic))['fr-copyright','fr-rights','fr-resale','mc-resale'].forEach(id=>ids.add(id));
 if(/vente|sell|sale|contrat|contract|facture|invoice/.test(topic))['fr-attribution','fr-sale','fr-vat','fr-vat-margin','fr-consumer','fr-registry'].forEach(id=>ids.add(id));
 if(/ivoire|ivory|cites|coral|ecaille/.test(topic))ids.add('cites');
 if(/irak|iraq|syrie|syria/.test(topic))ids.add('restricted-origin');
 const selected=SOURCES.filter(s=>ids.has(s.id));
 const ageDays=Math.floor((Date.now()-Date.parse(REVIEWED+'T00:00:00Z'))/86400000);
 return {version:'guide-4.1',reviewed:REVIEWED,coverage:p.coverage,freshness:ageDays>30?'revalidation-required':'within-editorial-review-window',policy:'Sources préchargées et sélectionnées sans recherche réseau. Ni qualification définitive ni vérification de sanctions en temps réel. Si revalidation-required, ne pas présenter les textes comme fraîchement vérifiés. Le code professionnel ne devient pas une loi universelle. Aucun pays non couvert ne reçoit une autorisation par défaut.',sources:selected,nextDocuments:documentsFor(r)};
}

/* WORLD REGISTRY 5.0 — original editorial summaries, not a mirror of legal databases.
 * A territory entry means routing support, never complete legal coverage.
 * Unknown/repealed/draft/future/stale/conflicting material cannot enter operative context.
 */
export const LEGAL_VERSION='world-5.0';
export const LEGAL_TOPICS=['export','import','customs','title','sale','consumer','tax','aml','sanctions','copyright','resale','species','ethics','records','restitution'];
const ISO_CODES='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ');
const regionFR=new Intl.DisplayNames(['fr'],{type:'region'}),regionEN=new Intl.DisplayNames(['en'],{type:'region'});
export const TERRITORIES=ISO_CODES.map(code=>({code,fr:regionFR.of(code),en:regionEN.of(code),coverage:'not-assessed'}));
const aliases=new Map();for(const t of TERRITORIES)for(const n of [t.code,t.fr,t.en])aliases.set(norm(n),t.code);
for(const [n,c]of Object.entries({'uk':'GB','united kingdom':'GB','royaume-uni':'GB','usa':'US','etats-unis':'US','etats unis':'US','chine continentale':'CN','mainland china':'CN','hong kong':'HK','macao':'MO','macau':'MO','tchequie':'CZ','republique tcheque':'CZ','coree du sud':'KR','coree du nord':'KP','russie':'RU','vietnam':'VN','taiwan':'TW','emirats arabes unis':'AE','uae':'AE','great britain':'GB-GBN','grande-bretagne':'GB-GBN','northern ireland':'GB-NIR','irlande du nord':'GB-NIR','dubai':'AE-DU','dubai emirate':'AE-DU'}))aliases.set(norm(n),c);
export function jurisdiction(value){return typeof value==='string'?aliases.get(norm(value))||null:null;}
const EU_ISO=new Set('AT BE BG HR CY CZ DK EE FI FR DE GR HU IE IT LV LT LU MT NL PL PT RO SK SI ES SE'.split(' '));
const parent=c=>c?.startsWith('GB-')?'GB':c?.startsWith('AE-')?'AE':c;
const inEUCustoms=c=>EU_ISO.has(c)||c==='MC'; // Other special territories require separate review, never inherit from a sovereign state.
const meta={};
function govern(ids,jurisdictions,topics,anchor,extra={}){for(const id of ids.split(' ')){const s=get(id);if(!s)throw Error('Missing legal source '+id);meta[id]={jurisdictions,topics,anchor,kind:'administrative-guidance',legalStatus:'reference-only',editorialStatus:'reviewed-summary',reviewed:REVIEWED,usableFrom:REVIEWED,usableUntil:null,reviewAfterDays:30,versionLabel:'Page officielle consultée ; consolidation intégrale non attestée',pinpoint:s.scope,evidence:[{url:s.url,observedAt:REVIEWED,finding:'Support de la synthèse thématique ; ne certifie pas tout le droit national.'}],...extra};}}
govern('ca-export',['CA'],['export'],'from');govern('jp-export',['JP'],['export'],'from');govern('au-export',['AU'],['export'],'from');
govern('uk-export',['GB'],['export'],'from');govern('uk-aml',['GB'],['aml'],'business');govern('ch-customs',['CH'],['import','export','customs'],'route');govern('ch-trade',['CH'],['aml','title'],'business');
govern('us-import',['US'],['import'],'to');govern('hk-declaration hk-customs',['HK'],['import','export','customs'],'route');govern('it-export',['IT'],['export'],'from');govern('de-export',['DE'],['export'],'from');
govern('cinoa-ethics',['WORLD'],['ethics'],'affiliation',{kind:'professional-code',legalStatus:'voluntary-standard',affiliation:'CINOA',usableFrom:'2024-07-05',versionLabel:'Code approuvé le 5 juillet 2024',pinpoint:'Provenance, titre, exactitude des descriptions, diligences'});
govern('fr-auction-ethics',['FR'],['ethics'],'business',{kind:'regulated-professional-code',legalStatus:'enacted-text',role:'auction-house',versionLabel:'Arrêté du 30 mars 2022 ; abroge celui du 21 février 2012',pinpoint:'Recueil annexé ; champ des ventes volontaires'});
govern('eu-customs-procedures',['EU-CUSTOMS'],['customs'],'route');govern('eu-import eu-thresholds',['EU-CUSTOMS'],['import'],'to');govern('monaco-customs',['MC'],['customs'],'route');
govern('india-export',['IN'],['export'],'from');govern('fr-export',['FR'],['export'],'from');govern('cites',['EU-CUSTOMS'],['species'],'route');
govern('fr-attribution fr-sale',['FR'],['sale'],'law');govern('fr-copyright fr-rights',['FR'],['copyright'],'publication');govern('fr-resale',['FR'],['resale'],'sale');govern('mc-resale',['MC'],['resale'],'sale');
govern('fr-aml',['FR'],['aml'],'business');govern('mc-aml',['MC'],['aml'],'business');govern('mc-patrimoine',['MC'],['export'],'from');govern('fr-vat fr-vat-margin',['FR'],['tax'],'tax');govern('fr-consumer',['FR'],['consumer'],'consumer');govern('fr-registry',['FR'],['records'],'business');govern('restricted-origin',['EU-CUSTOMS'],['import','sanctions'],'to');
// A broad code landing page cannot substantiate a specific contractual obligation.
meta['fr-sale'].editorialStatus='needs-review';meta['fr-sale'].versionLabel='Page générale du Code civil : articles et versions à qualifier';
meta['fr-rights'].editorialStatus='needs-review';meta['fr-rights'].versionLabel='La section liée ne suffit pas pour tous les articles de la fiche';
meta['eu-thresholds'].editorialStatus='superseded-reference';meta['eu-thresholds'].replacedBy='eu-icg-law';
// Prefer original national legislation over a secondary legal library.
get('india-export').url='https://www.indiacode.nic.in/bitstream/123456789/1693/1/A1972-52.pdf';
Object.assign(meta['india-export'],{kind:'legislation',legalStatus:'enacted-text',pinpoint:'Sections 2, 3 et 24 uniquement',versionLabel:'India Code, Act 52 of 1972 ; sections ciblées',evidence:[{url:get('india-export').url,observedAt:REVIEWED,finding:'Définitions, restriction de sortie et compétence ASI consultées. Historique territorial non consolidé.'}]});
function register(id,title,url,jurisdictions,topics,anchor,rule,extra={}){
 SOURCES.push({id,title,url,scope:extra.scope||jurisdictions.join(', ')+' · '+topics.join(', '),rule,reviewed:REVIEWED,reviewAfterDays:30,kind:extra.kind||'official-source'});
 govern(id,jurisdictions,topics,anchor,extra);
}
register('eu-icg-law','UE · règlement 2019/880 : art. 1 à 5, 16 et annexe','https://eur-lex.europa.eu/eli/reg/2019/880/oj/eng',['EU-CUSTOMS'],['import'],'to','Séparer interdiction d’introduction illicite et formalités ICG. Partie B : catégories archéologiques et éléments de monuments, plus de 250 ans ; partie C : catégories désignées, plus de 200 ans ET au moins 18 000 € par objet. Examiner lieu de création/découverte, sortie licite, régime et exceptions ; une absence de formalité ne vaut pas licéité.',{kind:'legislation',legalStatus:'enacted-text',usableFrom:'2025-06-28',pinpoint:'Art. 1–5, 16 ; annexe B/C',versionLabel:'Règles ICG opérationnelles depuis le 28 juin 2025 ; qualification de catégorie requise'});
register('eu-amlr-future','UE · règlement 2024/1624 : calendrier d’application','https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32024R1624',['EU'],['aml'],'business','L’entrée en vigueur du règlement ne doit pas être confondue avec son application générale le 10 juillet 2027. Les catégories particulières de l’article 3(3)(n)/(o) ont un autre calendrier. Ne pas remplacer prématurément les règles nationales applicables.',{kind:'legislation',legalStatus:'enacted-not-yet-applicable',usableFrom:'2027-07-10',pinpoint:'Article 90',versionLabel:'Calendrier uniquement ; obligations substantielles à qualifier avant activation'});
register('es-export-law','Espagne · Ley 16/1985, articles 5 et 29 à 33','https://www.boe.es/buscar/act.php?id=BOE-A-1985-12534&p=20260527&tn=1',['ES'],['export'],'from','Pour les biens du patrimoine espagnol, examiner l’autorisation préalable, l’Inventario General et les interdictions des biens protégés. Les sorties temporaires et les biens importés documentés ont des règles propres. Une demande avec valeur déclarée peut avoir des conséquences d’offre de vente à l’État : qualifier avant dépôt.',{kind:'legislation',legalStatus:'consolidated-reference',versionLabel:'Consolidation informative BOE, mise à jour publiée le 27 mai 2026',pinpoint:'Art. 5, 29–33 ; original officiel à rapprocher',authority:'Ministerio de Cultura / autorité compétente'});
register('be-export','Belgique · compétence export des biens à Bruxelles','https://economie.fgov.be/fr/themes/politique-commerciale/licences/exportation-de-biens-culturels',['BE'],['export'],'from','Identifier la région où se trouve le bien. Depuis le 11 décembre 2025, le SPF Économie traite les demandes de licence européenne des biens situés à Bruxelles-Capitale. Ne pas choisir la communauté sur la seule langue de l’utilisateur ; les protections patrimoniales restent distinctes.',{pinpoint:'Avis de changement de compétence du 11 décembre 2025',authority:'SPF Économie / communauté compétente selon localisation'});
register('be-import','Belgique · importations de biens culturels','https://economie.fgov.be/fr/themes/politique-commerciale/licences/importations-de-biens',['BE'],['import'],'to','Le SPF Économie oriente les formalités ICG. Documenter le pays de création ou découverte et la licéité de sortie ; les exigences européennes ne remplacent pas les protections belges.',{authority:'SPF Économie'});
register('za-export','Afrique du Sud · SAHRA, Heritage Objects','https://www.sahra.org.za/heritage-objects/',['ZA'],['export'],'from','Comparer l’objet à la List of Types et aux désignations spécifiques. Pour les catégories visées, déposer la demande de permis dans SAHRIS avant sortie, temporaire ou définitive. Les biens déclarés et collections ont aussi des contraintes de disposition ; le permis n’est pas acquis.',{authority:'SAHRA',pinpoint:'NHRA section 32 ; procédure SAHRIS'});
register('za-list-2019','Afrique du Sud · remplacement de la liste de 2002','https://www.sahra.org.za/updated-gazetted-list-of-types-heritage-objects/',['ZA'],['export'],'from','La liste publiée en 2019 remplace celle de 2002. Utiliser la version de la liste liée par SAHRA et qualifier la catégorie, sans réutiliser automatiquement un ancien formulaire ou les anciens seuils.',{versionLabel:'List of Types, Gazette 42407 du 18 avril 2019',authority:'SAHRA'});
register('nz-export-law','Nouvelle-Zélande · Protected Objects Act 1975','https://www.legislation.govt.nz/act/public/1975/41/en/2021-10-28.pdf',['NZ'],['export','import','title'],'route','Examiner la catégorie d’objet protégé, le registre et l’autorisation de sortie. Les objets enregistrés, les taonga tūturu et les biens étrangers illicitement exportés ou volés ont des régimes distincts. La version publiée au 28 octobre 2021 sert de repérage : confirmer sa consolidation actuelle avant conclusion.',{kind:'legislation',legalStatus:'historical-version-unconfirmed',editorialStatus:'needs-review',versionLabel:'Version 28 octobre 2021 ; actualité de consolidation à confirmer',authority:'Ministry for Culture and Heritage'});
register('mx-historical-export','Mexique · INAH, exportation de biens historiques','https://tramites.inah.gob.mx/INAH-01-002.html',['MX'],['export'],'from','INAH reçoit via VUCEM les demandes des monuments ou biens meubles historiques ; certaines catégories sont interdites de sortie définitive. Ne pas généraliser cette procédure aux antiquités archéologiques ni aux monuments artistiques relevant d’un autre institut. Réunir photographies et identification. Les tarifs affichés 2025 ne sont pas repris.',{authority:'INAH ; INBAL si catégorie artistique à confirmer',pinpoint:'Procédure INAH-01-002 ; exclusions de catégories'});
register('pe-nonheritage','Pérou · certification de non-appartenance au patrimoine','https://www.gob.pe/13499-obtener-la-certificacion-de-bien-mueble-no-perteneciente-al-patrimonio-cultural-para-exportacion',['PE'],['export'],'from','Pour les objets destinés à l’export qui nécessitent cette qualification, demander au ministère la certification de non-appartenance au patrimoine avec photographies. Ne pas présenter ce certificat comme une autorisation de vendre un bien patrimonial ; l’examen peut au contraire empêcher la sortie.',{authority:'Ministerio de Cultura'});
register('br-export','Brésil · IPHAN, Declaração de Saída de Bens Culturais','https://www.gov.br/pt-br/servicos/consultar-sobre-a-existencia-de-restricao-legal-para-saida-de-obras-de-arte-do-pais',['BR'],['export'],'from','La DSBC aide à déterminer si une intervention de l’IPHAN est nécessaire. Documenter protection, catégorie, datation et historique ; les biens tombados, archéologiques et certaines œuvres historiques demandent un examen spécifique. Ne pas imposer un permis identique à tout art contemporain.',{versionLabel:'Service mis à jour le 25 août 2026',authority:'IPHAN / Receita Federal'});
register('br-amendment','Brésil · Portaria 228/2019 modifiant la Portaria 44/2016','https://www.gov.br/iphan/pt-br/centrais-de-conteudo/legislacao/atos-normativos/2019/portaria-no-228-de-20-de-agosto-de-2019',['BR'],['export'],'from','La Portaria 44/2016 doit être lue avec sa modification de 2019, notamment la procédure de consultation en ligne. Une modification partielle ne signifie pas abrogation de tout le texte de 2016.',{kind:'legislation',legalStatus:'amending-text',pinpoint:'Portaria 228/2019 ; article 2 de la Portaria 44/2016'});
register('ar-reform','Argentine · décret 1037/2024','https://www.argentina.gob.ar/normativa/nacional/decreto-1037-2024-406488/texto',['AR'],['import','export'],'route','Pour les œuvres relevant de la loi 24.633, la réforme supprime l’ancien circuit général d’avis/licence et remplace les articles 1, 11 et 13. Elle abroge les articles 10 et 12 et le décret 217/2018. Les protections patrimoniales et formalités douanières demeurent à qualifier : aucune liberté générale de circulation pour tout objet culturel.',{kind:'legislation',legalStatus:'amending-text',usableFrom:'2024-11-25',pinpoint:'Art. 1–9 ; entrée en vigueur à la publication',authority:'Secretaría de Cultura / ARCA'});
register('tr-export','Turquie · ministère de la Culture, sortie de biens culturels','https://kvmgm.ktb.gov.tr/TR-132370/yurtdisina-kultur-varligi-cikarmak-istiyorum-ne-yapmaliyim.html',['TR'],['export'],'from','La loi 2863 encadre et interdit la sortie de biens mobiliers culturels ou naturels nécessitant protection, sous réserve des dispositifs particuliers. Faire déterminer la catégorie par le musée ou l’autorité compétente avant transport ; ne pas promettre un permis ordinaire pour un bien protégé.',{authority:'Ministère de la Culture et du Tourisme / musée compétent'});
register('ae-federal','Émirats arabes unis · loi fédérale 11/2017 sur les antiquités','https://uaelegislation.gov.ae/en/legislations/1236',['AE'],['export','import'],'route','Identifier l’émirat et la qualification d’antiquité ; rapprocher le texte fédéral, son règlement et la législation locale. Ne pas assimiler un port franc à une dispense culturelle. La fiche est un point d’orientation, pas une confirmation d’autorisation.',{kind:'legislation',legalStatus:'enacted-text',editorialStatus:'needs-review',pinpoint:'Texte fédéral et règlement à consolider',authority:'Ministry of Culture et autorité de l’émirat'});
register('ae-dubai-2026','Dubaï · loi 11/2026 sur les antiquités','https://dlp.dubai.gov.ae/Legislation%20Reference/2026/Law%20No.%20(11)%20of%202026%20Concerning%20Antiquities%20and%20Archaeological%20Sites.html',['AE-DU'],['import','export'],'route','Les articles 13 et 18 prévoient des approbations DCAA pour les antiquités, y compris l’entrée de certaines antiquités étrangères. L’article 27 comporte une transition ; l’article 30 rattache l’entrée en vigueur à la publication. Date de publication et règlements d’exécution à confirmer avant application. Le texte arabe prime la traduction anglaise.',{kind:'legislation',legalStatus:'commencement-unconfirmed',editorialStatus:'needs-review',pinpoint:'Art. 13, 18, 27, 30',versionLabel:'Loi datée du 11 mai 2026 ; commencement exact non établi',authority:'Dubai Culture and Arts Authority'});
register('cn-revision','Chine continentale · loi sur les biens culturels révisée en 2024','https://www.spp.gov.cn/spp/fl/202411/t20241109_671652.shtml',['CN'],['export','import','sale'],'route','Révision adoptée le 8 novembre 2024, applicable le 1er mars 2025. Ne plus utiliser les traductions anglaises de 2007/2015 pour décrire le régime actuel. Le texte chinois consolidé, les catégories de sortie et les mesures d’application exigent encore une lecture complète ; aucune règle de seuil n’est validée dans cette fiche.',{kind:'legislation',legalStatus:'revised-text',editorialStatus:'needs-review',usableFrom:'2025-03-01',pinpoint:'Révision 2024, date confirmée par la NCHA ; articles opérationnels non validés',evidence:[{url:'https://www.ncha.gov.cn/col/col2793/index.html',observedAt:REVIEWED,finding:'Révision et date d’application confirmées ; accès intégral non obtenu.'}],authority:'National Cultural Heritage Administration / GACC'});
register('ch-bilateral-2026','Suisse · accords bilatéraux de transfert','https://www.bak.admin.ch/en/bilateral-agreements',['CH'],['import'],'to','Qualifier pays d’origine, catégorie et accord bilatéral à la date du mouvement. La page OFC ajoute notamment les accords avec la Bolivie et la Côte d’Ivoire entrés en vigueur en 2026. L’existence d’un accord ne signifie pas que tout objet provenant de ce pays est interdit.',{pinpoint:'Accords en vigueur ; listes matérielles propres à chacun',authority:'Office fédéral de la culture'});
register('us-italy-2026','États-Unis · prolongation des restrictions archéologiques Italie','https://www.govinfo.gov/content/pkg/FR-2026-01-14/pdf/FR-2026-01-14.pdf',['US'],['import'],'to','CBP Dec. 26–01 prolonge jusqu’au 12 janvier 2031 les restrictions concernant les catégories archéologiques italiennes désignées. Examiner liste et exceptions de 19 CFR 12.104c ; ne pas en déduire un embargo sur toute peinture italienne. Le tableau général des autres pays reste à vérifier.',{kind:'legislation',legalStatus:'amending-text',usableFrom:'2026-01-12',usableUntil:'2031-01-12',origin:'IT',pinpoint:'CBP Dec. 26–01, modification de 19 CFR 12.104g(a)',authority:'CBP'});
register('icom-2026','ICOM · Code of Ethics for Museums, 2026','https://icom.museum/wp-content/uploads/2026/07/ICOM-Code-of-Ethics-for-Museums_2026_EN.pdf',['WORLD'],['ethics'],'profession','Pour les musées et professionnels concernés : provenance et titre, acquisitions responsables, documentation, conflits d’intérêts, collections et cessions. Engagement des membres ICOM ; référence non contraignante pour les non-membres. Ne pas transformer le code muséal en loi applicable à toute galerie.',{kind:'professional-code',legalStatus:'voluntary-standard',usableFrom:'2026-06-25',role:'museum',pinpoint:'Preamble : To Whom Does This Code Apply ; Collections ; Professionalism',versionLabel:'Adopté le 25 juin 2026 ; remplace la version 2004'});
register('unesco-ethics','UNESCO · déontologie des négociants, révision en cours','https://www.unesco.org/en/node/207439',['WORLD'],['ethics'],'profession','Les axes retenus sont provenance, diligence, coopération contre le trafic et restitution. La révision du code de 1999 est annoncée comme en cours : un projet ou rapport de consultation ne constitue pas un nouveau code adopté. Ne pas importer de règles détaillées non vérifiées.',{kind:'professional-code',legalStatus:'revision-in-progress',editorialStatus:'needs-review',pinpoint:'État de la révision, pas adoption d’un code nouveau'});
register('unidroit-status','UNIDROIT · Convention de 1995 : États parties et déclarations','https://www.unidroit.org/instruments/cultural-property/1995-convention/status/',['WORLD'],['restitution'],'risk','Avant d’invoquer la Convention de 1995, établir les États concernés, dates pertinentes, entrée en vigueur et déclarations. Ni la signature seule ni l’adhésion d’un seul pays ne suffisent à résoudre l’applicabilité. Les demandes de restitution restent distinctes des formalités douanières.',{kind:'treaty-status',legalStatus:'status-directory',pinpoint:'Table des États, dates et déclarations ; art. 10 à rapprocher'});
// Evidence of exclusions is preserved; excluded content is not passed to the model as operative rules.
export const LEGAL_EXCLUSIONS=[
 {id:'fr-auction-2012',jurisdiction:'FR',status:'repealed',replacement:'fr-auction-ethics',scope:'Arrêté du 21 février 2012',effectiveTo:'2022-04-08',evidence:'https://www.legifrance.gouv.fr/jorf/id/JORFARTI000045522972',reason:'Abrogation expresse par arrêté du 30 mars 2022 ; ne pas abroger tous les autres textes du métier.'},
 {id:'uk-aml-guide-2020',jurisdiction:'GB',status:'withdrawn-guidance',replacement:'uk-aml',scope:'Ancienne publication HMRC/BAMF',effectiveTo:null,evidence:'https://www.gov.uk/government/publications/art-market-participants-guidance-on-anti-money-laundering-supervision',reason:'Page signalée Withdrawn ; retrait du guide, pas abrogation des Money Laundering Regulations.'},
 {id:'ar-decree-217-2018',jurisdiction:'AR',status:'repealed',replacement:'ar-reform',scope:'Décret 217/2018',effectiveTo:'2024-11-25',evidence:get('ar-reform').url,reason:'Abrogation expresse article 6 du décret 1037/2024.'},
 {id:'ar-law-24633-old-10-12-13',jurisdiction:'AR',status:'partially-repealed-or-replaced',replacement:'ar-reform',scope:'Art. 10 et 12 abrogés ; art. 13 remplacé',effectiveTo:'2024-11-25',evidence:get('ar-reform').url,reason:'Ne pas marquer la loi 24.633 entière comme abrogée.'},
 {id:'icom-2004',jurisdiction:'WORLD',status:'superseded-standard',replacement:'icom-2026',scope:'Code ICOM 2004',effectiveTo:'2026-06-25',evidence:get('icom-2026').url,reason:'Code révisé adopté en 2026 ; anciennes numérotations non reprises automatiquement.'},
 {id:'icom-draft-2025',jurisdiction:'WORLD',status:'draft',replacement:'icom-2026',scope:'Second draft de consultation',effectiveTo:null,evidence:'https://icom.museum/wp-content/uploads/2025/03/ICOM-Code-of-Ethics_Revised-second-draft.pdf',reason:'Projet, pas norme adoptée.'},
 {id:'za-list-2002',jurisdiction:'ZA',status:'superseded-list',replacement:'za-list-2019',scope:'Ancienne List of Types',effectiveTo:'2019-04-18',evidence:get('za-list-2019').url,reason:'Remplacement annoncé explicitement par SAHRA.'},
 {id:'cn-english-2007-2015',jurisdiction:'CN',status:'superseded-translation',replacement:'cn-revision',scope:'Traductions de versions antérieures',effectiveTo:'2025-03-01',evidence:'https://www.ncha.gov.cn/col/col2793/index.html',reason:'Révision 2024 applicable en 2025 ; nouvelle version opérationnelle encore à valider.'},
 {id:'au-compilation-C2024C00100',jurisdiction:'AU',status:'superseded-version',replacement:'au-export',scope:'Compilation C20',effectiveTo:'2024-10-14',evidence:'https://www.legislation.gov.au/Details/C2024C00100',reason:'Registre : Superseded version, 20 mars–13 octobre 2024 ; loi elle-même non abrogée.'},
 {id:'fr-import-culture-old-page',jurisdiction:'FR',status:'conflicting-guidance',replacement:'eu-icg-law',scope:'Phrase limitant toute importation au seul contrôle douanier',effectiveTo:null,evidence:'https://www.culture.gouv.fr/thematiques/circulation-des-biens-culturels/pour-les-professionnels/comment-soumettre-une-demande-d-autorisation-d-exportation?lang=en',reason:'Phrase trop générale incompatible avec les formalités culturelles ICG ; ne pas invalider toute la page export.'}
];
for(const s of SOURCES){if(!meta[s.id])throw Error('Ungoverned source '+s.id);Object.assign(s,{governance:meta[s.id]});}

function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const d=new Date(value+'T00:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===value?value:null;}
export function sourceEligibility(source,options={}){
 const now=validDate(options.now||new Date().toISOString().slice(0,10)),at=validDate(options.at||now),g=source?.governance;
 if(!now||!at)return {eligible:false,reason:'invalid-date'};
 if(!g)return {eligible:false,reason:'unclassified-source'};
 if(g.editorialStatus!=='reviewed-summary')return {eligible:false,reason:g.editorialStatus||'needs-review'};
 if(!validDate(g.reviewed)||!g.evidence?.length)return {eligible:false,reason:'missing-evidence'};
 const age=(Date.parse(now)-Date.parse(g.reviewed))/86400000;
 if(age<0)return {eligible:false,reason:'review-after-assessment'};
 if(age>g.reviewAfterDays)return {eligible:false,reason:'review-expired'};
 if(!validDate(g.usableFrom)||at<g.usableFrom)return {eligible:false,reason:'date-outside-reviewed-scope'};
 if(g.usableFrom>now)return {eligible:false,reason:'future-rule-needs-review'};
 if(g.usableUntil&&at>=g.usableUntil)return {eligible:false,reason:'ended-version'};
 return {eligible:true,reason:'limited-editorial-summary',legalClearance:false};
}
const cleanRole=x=>/^(auction-house|maison de ventes|operateur de ventes|commissaire-priseur)$/.test(norm(x))?'auction-house':/^(museum|musee)$/.test(norm(x))?'museum':/^(gallery|galerie|dealer|marchand|courtier|broker)$/.test(norm(x))?'dealer':null;
function factsFor(r){return {from:jurisdiction(r.lieu),to:jurisdiction(r.dest),origin:jurisdiction(r.creation),business:jurisdiction(r.paysEtablissement),law:jurisdiction(r.droitApplicable),publication:jurisdiction(r.paysPublication),sale:jurisdiction(r.paysVente),tax:jurisdiction(r.paysFiscalite),consumer:jurisdiction(r.paysAcheteur),role:cleanRole(r.profession),affiliation:norm(r.affiliation)==='cinoa'?'CINOA':null};}
function topicsFor(r,message){const m=norm(message),set=new Set(['title','records']);
 if(['vente','achat'].includes(r.operation))for(const t of ['sale','aml','tax','resale','ethics','sanctions'])set.add(t);
 if(r.operation!=='archiver'&&r.lieu&&r.dest&&jurisdiction(r.lieu)!==jurisdiction(r.dest))for(const t of ['export','import','customs','sanctions'])set.add(t);
 const patterns={export:/export|sortie|expedi|transport/,import:/import|douan|custom|transport|entree/,customs:/douan|custom|ata|entrepot|free.?port/,copyright:/copyright|droit.*auteur|reproduct|image|deces|death|70 ans/,sale:/vente|sell|sale|contrat|contract/,consumer:/retract|withdraw|consumer|consommateur/,tax:/fiscal|tva|vat|tax/,aml:/blanch|launder|beneficiaire|kyc/,ethics:/deonto|ethic|cinoa|icom/,restitution:/restitu|spoli|stolen|vole|nazi|pillag/,species:/ivoire|ivory|cites|corail|coral|ecaille|tortoise|palis|rosewood/};
 for(const [t,p]of Object.entries(patterns))if(p.test(m))set.add(t);
 if(r.artisteNom)set.add('copyright');if(r.acheteur==='particulier'&&r.mode==='distance')set.add('consumer');
 if(r.protege==='oui'||r.protege==='inconnu'||patterns.species.test(norm(r.materiauxDetail)))set.add('species');
 if(/irak|iraq|syrie|syria|afghan|pillage|spolie|stolen|vole/.test(norm(r.origineCulturelle+' '+r.provenanceTexte)))set.add('restitution');
 return set;
}
function territorialMatch(g,f){
 const matches=c=>!!c&&g.jurisdictions.some(j=>j===c||(j==='GB'&&parent(c)==='GB')||(j==='AE'&&parent(c)==='AE')||(j==='EU'&&EU_ISO.has(c))||(j==='EU-CUSTOMS'&&inEUCustoms(c)));
 if(g.origin&&f.origin!==g.origin)return false;
 if(g.anchor==='affiliation')return f.affiliation===g.affiliation;
 if(g.anchor==='profession')return !!g.role&&f.role===g.role;
 if(g.anchor==='risk')return true;
 if(g.role&&f.role!==g.role)return false;
 if(g.anchor==='route')return matches(f.from)||matches(f.to);
 return matches(f[g.anchor]);
}
function mentionedCountries(message){const m=' '+norm(message).replace(/[^\p{L}\p{N}-]+/gu,' ')+' ';const out=new Set();for(const [name,code]of aliases)if(name.length>3&&m.includes(' '+name+' '))out.add(code);return [...out].slice(0,5);}
const DOC_PLAN=[
 {id:'identity',audiences:['professional','buyer','authority'],facts:['attribution','date','dimensions','materials'],request:'Photographies, facture, certificat ou catalogue ; rapprocher les descriptions sans transformer une hypothèse en certitude.'},
 {id:'title',audiences:['professional'],facts:['owner','authority-to-sell','provenance'],request:'Titre d’acquisition et mandat si représentation ; tracer les contradictions et les changements de propriétaire.'},
 {id:'movement',audiences:['authority','professional'],facts:['from','to','origin','movement-date','customs-procedure'],request:'Anciennes licences, déclarations douanières, transport et preuves de sortie ; une pièce reçue ne signifie pas démarche accomplie.'},
 {id:'sale',audiences:['buyer','professional'],facts:['parties','price-currency','attribution','delivery','mandatory-law'],request:'Préparer contrat, facture et remise à partir des faits validés ; vérifier les droits impératifs et les mentions requises.'}
];
export function promptContext(r={},message='',options={}){
 const now=validDate(options.now||new Date().toISOString().slice(0,10));
 const givenDate=r.dateOperation,at=givenDate?validDate(givenDate):now,f=factsFor(r),topics=topicsFor(r,message);
 const moving=r.operation!=='archiver'&&!!f.from&&!!f.to&&f.from!==f.to;
 const inquiry=mentionedCountries(message); // Retrieval hint only, never a factual route or choice of law.
 const sources=[],withheld=[],upcoming=[];
 for(const s of SOURCES){const g=s.governance;if(!g.topics.some(t=>topics.has(t)))continue;
  let match=territorialMatch(g,f),basis='declared-facts';
  if(!match&&inquiry.some(c=>g.jurisdictions.includes(c))){match=true;basis='question-context-only';}
  if(!match)continue;
  if(!moving&&!/export|import|transport|sortie|douan|custom/i.test(message)&&['from','to','route'].includes(g.anchor)&&g.topics.every(t=>['import','export','customs'].includes(t)))continue;
  const eligible=sourceEligibility(s,{now,at:at||'invalid'});
  if(!eligible.eligible){withheld.push({id:s.id,title:s.title,reason:eligible.reason,url:s.url,authority:g.authority||null});if(g.usableFrom>now)upcoming.push({id:s.id,date:g.usableFrom,title:s.title});continue;}
  sources.push({id:s.id,title:s.title,url:s.url,scope:s.scope,rule:s.rule,reviewed:g.reviewed,kind:g.kind,legalStatus:g.legalStatus,version:g.versionLabel,pinpoint:g.pinpoint,usableFrom:g.usableFrom,usableUntil:g.usableUntil,selectionBasis:basis,applicability:'conditions-to-establish'});
 }
 const related=[...new Set(Object.values(f).filter(x=>typeof x==='string'&&(ISO_CODES.includes(x)||x.includes('-'))).filter(x=>!['auction-house'].includes(x)))];
 const coverage=related.map(code=>({territory:code,topics:[...topics].map(topic=>({topic,status:sources.some(s=>s.selectionBasis==='declared-facts'&&s.governance===undefined&&meta[s.id].topics.includes(topic)&&meta[s.id].jurisdictions.some(j=>j===code||j===parent(code)||(j==='EU-CUSTOMS'&&inEUCustoms(code))||(j==='EU'&&EU_ISO.has(code))))?'partial':'not-assessed'}))}));
 const gaps=[];
 if(!at)gaps.push({id:'invalid-operation-date',action:'Confirmer une date valide avant sélection des versions.'});
 if(moving){for(const [field,topic]of [['from','export'],['to','import']])if(!sources.some(s=>s.selectionBasis==='declared-facts'&&meta[s.id].topics.includes(topic)&&territorialMatch({...meta[s.id],anchor:field},f)))gaps.push({id:'local-'+topic,territory:f[field],action:'Qualifier le régime local auprès de l’autorité du patrimoine et des douanes avant toute conclusion.'});if(!r.dateOperation)gaps.push({id:'operation-date',field:'dateOperation',action:'Déterminer la date prévue du mouvement ; la sélection actuelle est provisoire.'});}
 if(['vente','achat'].includes(r.operation)&&!f.business)gaps.push({id:'business-country',field:'paysEtablissement',action:'Identifier le pays d’établissement du professionnel, sans le déduire du lieu de l’œuvre.'});
 if(topics.has('copyright')&&!f.publication)gaps.push({id:'publication-country',field:'paysPublication',action:'Identifier le territoire d’utilisation des images ; aucune durée mondiale uniforme.'});
 if(topics.has('sale')&&!f.law)gaps.push({id:'contract-law',field:'droitApplicable',action:'Qualifier les pays des parties et de la vente ; une clause de choix de loi ne neutralise pas les lois impératives.'});
 if([...related].some(c=>c==='GB'))gaps.push({id:'uk-region',action:'Préciser Grande-Bretagne ou Irlande du Nord avant formalités.'});
 if(related.some(c=>parent(c)==='AE'))gaps.push({id:'emirate',action:'Confirmer l’émirat et la législation locale ; aucune assimilation automatique aux ports francs.'});
 if(topics.has('species'))gaps.push({id:'live-species-review',action:'Identifier espèce, composant et historique puis consulter les annexes et règles nationales actuelles ; aucune vérification CITES effective dans ce moteur.'});
 if(topics.has('sanctions'))gaps.push({id:'live-sanctions-review',action:'Contrôle actualisé des parties, bénéficiaires, banques, origine et destinations requis ; aucun résultat de filtrage réel produit par ce corpus.'});
 if(topics.has('restitution'))gaps.push({id:'historical-law',action:'Reconstituer chaque acquisition et sortie avec pays et date. Les versions historiques ne sont pas automatiquement validées par la présente sélection.'});
 const exclusions=LEGAL_EXCLUSIONS.filter(x=>related.some(c=>parent(c)===x.jurisdiction)||(x.jurisdiction==='WORLD'&&topics.has('ethics'))).map(x=>({id:x.id,status:x.status,replacement:x.replacement,scope:x.scope}));
 // Full source manifest lives in the delivery. Prompt budgets never silently drop a topic.
 const maxSources=Math.max(1,Math.min(18,Number(options.maxSources)||18));
 if(sources.length>maxSources){for(const s of sources.slice(maxSources))withheld.push({id:s.id,reason:'context-budget-not-loaded',title:s.title,url:s.url});gaps.push({id:'context-budget',action:'Traiter le point prioritaire puis qualifier les autres thèmes ; aucune exhaustivité dans cette réponse.'});}
 return {version:LEGAL_VERSION,reviewed:REVIEWED,asOf:now,operationDate:at,operationDateConfirmed:!!validDate(givenDate),freshness:withheld.some(x=>x.reason==='review-expired')?'revalidation-required':'limited-editorial-review',coverage,exhaustive:false,legalClearance:false,
 policy:'Ni qualification définitive ni vérification en temps réel. Seules sources[] fournissent les synthèses autorisées, dans leur champ et version. question-context-only est une piste hypothétique, jamais un fait du dossier. withheld/exclusions/upcoming ne sont pas des règles opératoires. Une absence de règle est une lacune, pas une exemption. Lois, guides et codes privés ont des portées distinctes. Les faits extraits sont à confirmer. Les lois impératives et conflits de lois exigent qualification ; aucun choix par simple score, langue, nationalité de l’artiste ou pays stylistique. Aucun seuil absent de sources[] ne doit être inventé. Demander une seule pièce ou précision décisive et expliquer son utilité.',
 sources:sources.slice(0,maxSources),withheld,upcoming,exclusions,gaps,nextDocuments:documentsFor(r),documentPlan:DOC_PLAN.filter(x=>x.id!=='movement'||moving).filter(x=>x.id!=='sale'||['vente','achat'].includes(r.operation)),historyPolicy:'Conserver les versions retirées avec preuve et relations ; pas de réapplication historique sans période et territoire vérifiés.'};
}
export function coverageManifest(){return {version:LEGAL_VERSION,reviewed:REVIEWED,complete:false,territories:TERRITORIES.map(t=>({...t,topics:LEGAL_TOPICS.map(topic=>({topic,sources:SOURCES.filter(s=>s.governance.jurisdictions.includes(t.code)&&s.governance.topics.includes(topic)).map(s=>({id:s.id,status:s.governance.editorialStatus})),status:SOURCES.some(s=>s.governance.jurisdictions.includes(t.code)&&s.governance.topics.includes(topic)&&sourceEligibility(s).eligible)?'partial':'not-assessed'}))})),exclusions:LEGAL_EXCLUSIONS};}

// The visible journey and server advice use the same eligibility gate.
export function plan(r={},lang='fr',year=new Date().getFullYear()){
 const previous=originalPlan(r,lang,year),ctx=promptContext(r),allowed=new Set(ctx.sources.filter(s=>s.selectionBasis==='declared-facts').map(s=>s.id));
 const generic=tr(lang,'Ajoutez vos justificatifs : nous pourrons préciser cette démarche à partir du trajet et de la situation de l’œuvre.','Add the supporting records so this step can be assessed against the route and the work’s circumstances.');
 const items=previous.items.map(item=>{
  const refs=item.sources.map(s=>s.id==='eu-thresholds'?get('eu-icg-law'):s).filter(s=>s&&allowed.has(s.id));
  const missing=item.sources.length&&refs.length<item.sources.length;
  return {...item,sources:refs,detail:missing?generic:item.detail,status:missing?'qualification-required':item.status};
 });
 const represented=new Set(items.flatMap(i=>i.sources.map(s=>s.id)));
 for(const s of ctx.sources){if(s.selectionBasis!=='declared-facts'||represented.has(s.id)||!['from','to','route'].includes(meta[s.id].anchor))continue;
  items.push({id:'world-'+s.id,title:tr(lang,'Préparer les documents locaux','Prepare the local documents'),detail:tr(lang,'Pour ce trajet, rapprochons la facture, les photographies et les anciens documents de circulation des exigences de l’autorité compétente.','For this route, compare the invoice, photographs and previous movement records with the relevant authority’s requirements.'),sources:[get(s.id)],priority:2,status:'to-review'});
 }
 return {...previous,version:LEGAL_VERSION,items,coverage:'Registre mondial de routage ; couverture juridique partielle par territoire et thème. Versions non vérifiées, périmées, remplacées ou non encore applicables exclues des conseils opératoires.',legalCoverage:ctx.coverage};
}
