/* ARTVELCHIV — curated legal guidance, not a legal-clearance engine.
 * Every source has a defined scope. No source updates or filings are implied.
 * Shared by the interface and both language-model providers. No private data here.
 */
export const REVIEWED='2026-10-04';
const source=(id,title,url,scope,rule)=>({id,title,url,scope,rule,reviewed:REVIEWED,kind:id==='cinoa-ethics'?'professional-code':'official-source',reviewAfterDays:30});
export const SOURCES=[
 source("ca-export","Canada · guide de l’exportation des biens culturels","https://www.canada.ca/en/canadian-heritage/services/export-permits-cultural-property/guide-exporting.html","Sortie du Canada","Appliquer les critères cumulés de la Liste de contrôle à la catégorie : âge, auteur décédé lorsque pertinent et seuils particuliers. Distinguer permis temporaire, permanent et général ; la demande relève d’un résident canadien et les autres restrictions demeurent. Ne pas transformer un seul seuil d’âge en autorisation."),
 source("jp-export","Japon · Agency for Cultural Affairs","https://www.bunka.go.jp/english/policy/cultural_properties/international/","Sortie du Japon","Les catégories désignées, notamment trésors nationaux et biens culturels importants, sont en principe interdites d’exportation, sous réserve des exceptions. Pour les objets d’art ancien, examiner le certificat attestant l’absence de désignation, Kobijutsuhin yushutsu kansa shomei, auprès de l’Agence ; ne pas le confondre avec une expertise d’authenticité."),
 source("au-export","Australie · Office for the Arts, exportation","https://www.arts.gov.au/what-we-do/cultural-heritage/movable-cultural-heritage/exporting-cultural-property-australia","Sortie d’Australie","Rapprocher l’objet de la National Cultural Heritage Control List et du registre des refus. Le régime distingue objets protégés de classes A/B, permis, interdictions et exemptions. Certains prêts entrants exigent une exemption avant arrivée pour préparer la réexportation ; les procédures peuvent prendre plusieurs mois."),

 source("uk-export","Royaume-Uni · exportation des biens culturels","https://www.gov.uk/guidance/export-art-antiques-and-cultural-goods-special-rules","Départ de Grande-Bretagne ou d’Irlande du Nord","Arts Council England administre les licences. Déterminer la localisation exacte : les procédures diffèrent entre Grande-Bretagne et Irlande du Nord. Vérifier catégorie, seuils et licence générale avant de choisir la demande ; conserver la licence délivrée avec la déclaration douanière. Une licence britannique ne vaut pas licence de sortie d’un État membre de l’UE."),
 source("uk-aml","Royaume-Uni · HMRC, art market participants","https://www.gov.uk/guidance/money-laundering-supervision-for-art-market-participants","Professionnels relevant des Money Laundering Regulations britanniques","L’activité professionnelle de commerce ou d’intermédiation sur des œuvres, pour une transaction ou des opérations liées d’au moins 10 000 euros, peut imposer enregistrement et vigilance HMRC. Examiner la définition fiscale d’œuvre, le rôle réel et les exceptions ; ne pas confondre simple conseil et intermédiation active."),
 source("ch-customs","Suisse · OFC, importation, transit et exportation","https://www.bak.admin.ch/en/import-transit-and-export-of-cultural-property","Biens culturels au sens de la LTBC suisse","Les biens culturels doivent être déclarés comme tels à la douane, y compris pour le dépôt en entrepôt. La révision de l’ordonnance entrée en vigueur le 1er janvier 2026 ajoute notamment datation et dimensions aux informations de déclaration. Examiner les accords bilatéraux et les restrictions applicables avant de conclure sur l’admission."),
 source("ch-trade","Suisse · OFC, commerce d’art et ventes aux enchères","https://www.bak.admin.ch/en/informations-for-the-art-trade","Professionnels concernés par la LTBC en Suisse","Documenter l’identité du cédant et son pouvoir de disposition ; obtenir sa déclaration écrite sur ce pouvoir. Rapprocher provenance, acquisition et obligations de diligence du guide OFC en vigueur. Une déclaration du vendeur ne remplace pas les autres vérifications."),
 source("us-import","États-Unis · CBP, objets d’art et antiquités","https://www.help.cbp.gov/s/article/Article1143?language=en_US","Importation aux États-Unis ; classement tarifaire et licéité distincts","Documenter âge, catégorie, valeur et origine pour le classement douanier. Examiner séparément les restrictions culturelles et les accords applicables, notamment sous 19 CFR 12.104g. Un classement tarifaire favorable ne démontre ni exportation licite ni droit d’importer. Ne pas promettre une absence totale de droits, taxes ou frais sur cette seule fiche."),
 source("hk-declaration","Hong Kong · déclaration d’importation et d’exportation","https://www.customs.gov.hk/en/service-enforcement-information/cargo-clearance/import-export-declaration/","Importations et exportations à Hong Kong, hors marchandises exemptées","Une déclaration exacte et complète est en principe requise dans les 14 jours suivant l’importation ou l’exportation, sous réserve des exemptions. Préparer facture, manifeste et description avec le transporteur. Ce délai déclaratif ne remplace pas les autorisations éventuellement exigées avant mouvement."),
 source("hk-customs","Hong Kong · contrôle des marchandises","https://www.customs.gov.hk/en/service-enforcement-information/cargo-clearance/","Territoire douanier de Hong Kong","Le régime de port franc n’efface pas les contrôles douaniers, déclarations ni restrictions. Ne pas transposer les règles de Chine continentale à Hong Kong ; examiner séparément la sortie du pays précédent, notamment si le bien vient de Chine continentale, et les composants protégés."),
 source("it-export","Italie · ministère de la Culture, plateforme SUE","https://sue.cultura.gov.it/","Sortie ou entrée de biens culturels en Italie","SUE traite notamment ALC, LED, sorties temporaires, déclarations et certificats d’entrée CAS/CAI. Le portail distingue depuis mai 2026 les circuits des biens artistiques et ceux des livres/archives et leurs déclarations de valeur. Identifier la catégorie et le bureau compétent ; ne pas appliquer un seuil unique à tous les objets ni confondre ancienneté de l’œuvre et durée des droits d’auteur."),
 source("de-export","Allemagne · guide des autorisations KGSG","https://www.kulturgutschutz-deutschland.de/SharedDocs/Downloads/DE/Merkblaetter/Flowchart.html?nn=124576","Sortie d’Allemagne","La procédure dépend de la protection nationale, de la destination, de la catégorie, de l’âge et de la valeur. Utiliser le parcours officiel de détermination de l’autorisation ; les règles européennes ne remplacent pas le KGSG national."),
 source("cinoa-ethics","CINOA · code de déontologie et charte, 2024","https://www.cinoa.org/about/code-of-ethics/","Code professionnel ; portée selon adhésion et engagements, pas loi universelle","Documenter la provenance et le titre, proportionner les diligences aux risques et donner une description exacte, y compris les réserves. Le code concerne les organisations membres et leurs membres selon leur cadre ; ses recommandations ne sont pas automatiquement des obligations légales de tout marchand."),
 source("fr-auction-ethics","France · recueil déontologique des ventes volontaires, 2022","https://www.legifrance.gouv.fr/jorf/id/JORFARTI000045522972","Opérateurs et commissaires-priseurs de ventes volontaires français","Le recueil approuvé le 30 mars 2022 prévoit des diligences sur identification, authenticité, provenance, droits du vendeur et composants réglementés. Ne pas dissimuler les doutes ; en cas de doute sur l’origine illicite, examiner abstention et information des autorités selon les textes. Ne pas transposer ce statut à toute galerie."),

 source('eu-customs-procedures','UE · régimes particuliers et carnet ATA','https://www.douane.gouv.fr/dossier/les-regimes-particuliers','Biens non Union sous régime particulier','L’admission temporaire et l’entrepôt permettent certains usages ou stockages en suspension de droits et taxes. Les conditions de vente, mise en libre pratique, réexportation et délais dépendent du régime et de l’autorisation. Lire la déclaration et consulter le représentant en douane avant livraison.'),
 source('eu-import','UE · règlement 2019/880 et mise en œuvre 2021/1079','https://www.douane.gouv.fr/demarche/importer-des-biens-culturels','Entrée dans le territoire douanier de l’Union de biens créés ou découverts hors UE','L’introduction de biens culturels illicitement exportés est interdite. Depuis le 28 juin 2025, les parties B et C imposent respectivement une licence ou une déclaration ICG. Les exceptions et le pays dont il faut prouver la sortie licite nécessitent l’historique du bien. L’article L111-8 du code du patrimoine a ses propres conditions cumulatives ; pas de permis d’origine universel.'),
 source('eu-thresholds','UE · catégories et seuils des formalités ICG','https://www.douane.gouv.fr/sites/default/files/2023-05/17/biens-culturels-reglementation-europeenne-applicable-a-l-introduction-et-a-l-importation.pdf','Biens entrant dans les catégories précises de l’annexe 2019/880','Partie B : biens archéologiques et éléments de monuments démembrés de plus de 250 ans, sans seuil de valeur. Partie C : catégories visées de plus de 200 ans, valeur d’au moins 18 000 € par objet. Âge, catégorie et valeur sont cumulatifs en C. Une sculpture ancienne n’est pas nécessairement archéologique. Ne jamais déduire une exemption générale de l’absence de formalité ICG.'),
 source('monaco-customs','Monaco · territoire douanier (CDU, article 4)','https://www.douane.gouv.fr/sites/default/files/2024-03/01/Manuel-transit-preuve-du-statut-p77-a-183.pdf','Circulation vers ou depuis Monaco','Monaco appartient au territoire douanier de l’Union en vertu de la convention douanière franco-monégasque. Ce n’est pas un État membre de l’UE. Cette inclusion ne rend pas automatiquement applicables toutes les règles civiles, fiscales, de consommation ou de propriété intellectuelle françaises.'),
 source('india-export','Inde · Antiquities and Art Treasures Act 1972, sections 2–3','https://www.wipo.int/wipolex/en/legislation/details/14946','Sortie physique d’Inde','Les antiquités visées comprennent notamment les objets ayant au moins 100 ans et certains manuscrits ou documents ayant au moins 75 ans. Les art treasures sont désignés par notification. Leur exportation est réservée au gouvernement central ou à une autorité/agence autorisée : ce n’est pas un permis ordinaire ouvert à tout vendeur. Faire confirmer la catégorie par l’ASI et les douanes avant expédition. Une origine stylistique indienne ne prouve pas une sortie actuelle d’Inde.'),
 source('fr-export','France · exportation des biens culturels','https://www.douane.gouv.fr/demarche/exporter-des-biens-culturels','Sortie de France ou du territoire douanier de l’Union','Distinguer certificat national / autorisation de sortie temporaire et licence européenne d’exportation (règlement 116/2009). Les seuils varient par catégorie, ancienneté et valeur ; ne pas réutiliser les seuils ICG d’importation. Les trésors nationaux relèvent d’une sortie temporaire. Examiner la durée de présence en France et le régime temporaire avant de conclure.'),
 source('cites','Espèces protégées · CITES et règlement 338/97','https://www.douane.gouv.fr/demarche/importer-des-specimens-cites','Objets comprenant des espèces animales ou végétales réglementées','Les documents dépendent de l’espèce, de l’annexe, du trajet, de la date et du régime. L’ancienneté ne dispense pas automatiquement de permis ou de certificat. Identifier les composants ; examiner les permis d’exportation/réexportation et d’importation avant transport. En France, service CITES compétent, généralement DREAL/DRIEAT/DEAL.'),
 source('fr-attribution','France · décret 81-255, articles 1 à 8','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000684875/','Descriptions et vente d’œuvres ou objets de collection en France','Le nom de l’artiste, la datation et les expressions d’attribution ont des effets distincts. « Attribué à » n’équivaut pas à une œuvre garantie de la main de l’artiste ; « d’après » doit rester distinct. Décrire les reproductions et les parties postérieures. Rapprocher les affirmations du catalogue, du certificat et de la facture avant de rédiger le contrat.'),
 source('fr-copyright','France · CPI L123-1 (durée des droits patrimoniaux)','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006278937','Durée ordinaire de protection en France','La règle ordinaire couvre la vie de l’auteur puis l’année du décès et les 70 années suivantes. Le repère de fin est le 31 décembre de l’année du décès + 70, sous réserve des régimes spéciaux et internationaux. L’âge de l’objet n’est pas la date de décès de l’artiste. Une notice biographique ne vaut pas autorisation d’utilisation.'),
 source('fr-rights','France · CPI L111-3 et L121-1','https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006069414/LEGISCTA000006133323/','Propriété matérielle, reproduction et droit moral','Acheter l’objet ne transfère pas automatiquement les droits d’auteur. Le droit moral reste protégé en France indépendamment de l’expiration des droits patrimoniaux. Examiner séparément vente matérielle, publication des images et autorisations ; ne pas appeler une œuvre « libre de tous droits » sur la seule base d’une date.'),
 source('fr-resale','France · CPI L122-8, droit de suite','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033688066','Reventes d’originaux avec intervention d’un professionnel en France','Le droit de suite dépend notamment de l’originalité/édition, de l’auteur et de ses ayants droit, de la revente, du professionnel et des conditions territoriales et financières. Une date de décès ne suffit pas à qualifier toute la vente. Identifier le bénéficiaire et l’organisme compétent avant de calculer ou d’attribuer des frais.'),
 source('mc-resale','Monaco · loi 1.526 du 1er juillet 2022','https://journaldemonaco.gouv.mc/Journaux/2022/Journal-8599/Loi-n-1.526-du-1er-juillet-2022-relative-au-droit-de-suite','Droit de suite monégasque','Monaco dispose d’un régime propre de droit de suite. Ne pas appliquer automatiquement les modalités françaises ; vérifier les conditions et le texte d’application monégasque pour la transaction.'),
 source('fr-aml','France · vigilance des marchands d’art et d’antiquités','https://www.douane.gouv.fr/fiche/marchands-dart-et-dantiquites','Professionnels assujettis en France','Le secteur est assujetti à la lutte contre le blanchiment pour les transactions ou séries liées d’au moins 10 000 €. Identifier client, représentation et bénéficiaire effectif, apprécier le risque et conserver les justificatifs selon le cadre applicable. Ne pas conclure qu’un montant inférieur exclut tout contrôle. Les vérifications internes ne sont pas des annexes publiques du dossier acheteur.'),
 source('mc-aml','Monaco · loi 1.362 et ordonnance 2.318','https://legimonaco.mc/tnc/loi/2009/08-03-1.362','Professionnels assujettis à Monaco','Le régime monégasque de vigilance doit être examiné selon la catégorie de professionnel et l’opération. Ne pas transposer les seuils français ni confondre art et autres objets de valeur. Vérifier la loi et son ordonnance d’application auprès du dispositif monégasque compétent avant de conclure.'),
 source('mc-patrimoine','Monaco · loi 1.446 sur le patrimoine national','https://legimonaco.mc/tnc/loi/2017/06-12-1.446/','Protection patrimoniale à Monaco','Examiner la protection patrimoniale locale et les éventuelles restrictions avant une sortie. L’union douanière n’écarte pas les règles monégasques du patrimoine. Ce repère ne permet pas, seul, de calculer les autorisations requises.'),
 source('fr-vat','France · BOI-TVA-SECT-90-40, version du 14 mai 2025','https://bofip.impots.gouv.fr/bofip/1285-PGP.html/identifiant=BOI-TVA-SECT-90-40-20250514','TVA française des œuvres d’art, objets de collection et antiquités fiscalement qualifiés','Depuis le 1er janvier 2025, les livraisons qualifiées relèvent du taux réduit de 5,5 %, sauf application du régime de la marge. Le régime dépend de l’acquisition, du vendeur et de l’opération. Ne pas présumer la TVA ni étendre le taux à tout objet de valeur. Importation, livraison et marge doivent rester distinctes.'),
 source('fr-vat-margin','France · BOI-TVA-SECT-90-20-20','https://bofip.impots.gouv.fr/bofip/13268-PGP.html/identifiant=BOI-TVA-SECT-90-20-20-20250514','Assujettis-revendeurs et régime de la marge','Examiner la facture d’achat et la qualité du cédant avant de proposer le régime de la marge. Ne pas cumuler automatiquement marge et taux réduit de 5,5 %. Une facture ne prouve pas à elle seule l’acquittement de TVA d’importation.'),
 source('fr-consumer','France · Code de la consommation, L221-18','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032226842','Contrats à distance ou hors établissement avec un consommateur lorsque le droit français s’applique','Le délai de rétractation de principe est de 14 jours, sous réserve du champ du texte et des exceptions. Les ventes aux enchères publiques et les ventes en ligne ne sont pas assimilables sans examen. Prévoir informations précontractuelles, garanties et modalités de retour selon le contrat ; ne pas supprimer des droits impératifs.'),
 source('fr-registry','France · Code pénal, article 321-7','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000023717783','Professionnels concernés par le registre des objets mobiliers','Certaines activités de vente de biens mobiliers usagés ou acquis hors fabrication/commerce imposent un registre. Conserver identification, provenance et vendeur. Une archive Artvelchiv n’est pas automatiquement un registre réglementaire conforme.'),
 source('fr-sale','France · Code civil, vente et garanties','https://www.legifrance.gouv.fr/codes/id/LEGITEXT000006070721','Vente soumise au droit français','Examiner information et consentement, délivrance, garantie d’éviction (1626) et vices cachés (1641). Définir objet/attribution, parties et mandat, prix et fiscalité, paiement, livraison, assurance et réserves. Les garanties impératives et règles de conflit ne peuvent être écartées par une simple clause modèle.'),
 source('restricted-origin','UE · biens culturels irakiens et syriens','https://www.douane.gouv.fr/demarche/importer-des-biens-culturels','Provenance irakienne ou syrienne','Des restrictions spécifiques s’ajoutent au régime général. Reconstituer les dates et circonstances de sortie et consulter les règlements 1210/2003 (Irak) et 36/2012 modifié notamment par 1332/2013 (Syrie). Ne pas conclure à une circulation autorisée sans examen des justificatifs et exceptions.')
];
const get=id=>SOURCES.find(s=>s.id===id);
const norm=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const EU=['france','allemagne','autriche','belgique','bulgarie','chypre','croatie','danemark','espagne','estonie','finlande','grece','hongrie','irlande','italie','lettonie','lituanie','luxembourg','malte','pays-bas','pologne','portugal','republique tcheque','tchequie','roumanie','slovaquie','slovenie','suede'];
export const isEU=x=>EU.includes(norm(x));
export const isCustomsUnion=x=>isEU(x)||norm(x)==='monaco';
const tr=(lang,fr,en)=>lang==='en'?en:fr;
export function artistTerm(record,year=new Date().getFullYear()){
 const values=[...new Set((record.artistReference?.death||[]).map(String).filter(x=>/^\d{4}$/.test(x)).map(Number))];
 if(values.length!==1||values[0]>year||values[0]<1)return null;
 const death=values[0];return {death,ordinaryEndYear:death+70,ordinaryExpired:year>death+70,scope:'France',clearance:false};
}
export function documentsFor(r,lang='fr'){
 const out=[{id:'acquisition',title:tr(lang,'Facture ou bordereau d’achat','Purchase invoice or auction receipt'),why:tr(lang,'Pour retrouver l’acquisition, le vendeur et la description d’origine.','To recover the acquisition details, seller and original description.')},{id:'identity',title:tr(lang,'Certificat, expertise ou ancien catalogue','Certificate, expert opinion or previous catalogue'),why:tr(lang,'Pour préciser l’artiste, la date et les matériaux.','To establish the recorded attribution, date and materials.')}];
 if(r.lieu&&r.dest&&r.lieu!==r.dest||r.arrivee==='importee'||r.douaneDocument)out.push({id:'transport',title:tr(lang,'Documents de transport ou de douane','Shipping or customs documents'),why:tr(lang,'Pour lire le trajet, le régime déclaré et les éventuelles échéances.','To identify the route, declared procedure and any deadlines.')});
 if(r.role==='mandataire')out.push({id:'mandate',title:tr(lang,'Mandat du propriétaire','Owner’s mandate'),why:tr(lang,'Pour préciser qui peut vendre et signer.','To establish authority to sell and sign.')});
 if(r.protege==='oui'||r.protege==='inconnu'||/ivoire|ivory|corail|coral|ecaille|tortoise/i.test(norm(r.materiauxDetail)))out.push({id:'materials',title:tr(lang,'Justificatif des matériaux','Material identification or permit'),why:tr(lang,'Pour examiner les composants réglementés.','To assess regulated components.')});
 return out;
}
export function plan(r={},lang='fr',year=new Date().getFullYear()){
 const items=[];const add=(id,fr,en,detailFR,detailEN,refs,priority=2)=>items.push({id,title:tr(lang,fr,en),detail:tr(lang,detailFR,detailEN),sources:refs.map(get).filter(Boolean),priority,status:'to-review'});
 const from=norm(r.lieu),to=norm(r.dest),creation=norm(r.creation),sale=['vente','achat'].includes(r.operation),archive=r.operation==='archiver';
 const moving=!!(from&&to&&from!==to&&!archive),incoming=moving&&!isCustomsUnion(from)&&isCustomsUnion(to),age=Number.isFinite(Number(r.annee))&&r.annee!==''&&r.annee!=null?year-Number(r.annee):null;
 if(moving&&from==='inde')add('india','Vérifier la sortie d’Inde avant le transport','Check export eligibility before shipping from India',age!==null&&age>=100?'Cette datation place l’objet dans une tranche d’âge susceptible de relever de l’interdiction d’exportation des antiquités. Demandez une confirmation de classement à l’ASI avec la facture, les photos et la datation ; une licence ordinaire ne suffit pas.':'La sortie dépend de l’âge, de la catégorie et d’un éventuel classement. Joignez facture, photos et datation : il faut d’abord écarter les restrictions indiennes, avant d’organiser le transport.',age!==null&&age>=100?'This date puts the object within an age range potentially covered by India’s antiquities export prohibition. Ask the ASI to confirm its classification using the invoice, photographs and dating evidence; an ordinary export permit is not sufficient.':'Export depends on age, category and any protected designation. Supply the invoice, photographs and dating evidence so Indian restrictions can be checked before shipping.',['india-export'],0);
 if(incoming){
  add('import','Préparer l’entrée à destination','Prepare the import at destination',to==='monaco'?'Monaco fait partie du territoire douanier de l’Union. Réunissez facture, provenance et justificatifs de sortie licite ; nous distinguons ensuite les documents culturels du dédouanement.':'Réunissez facture, provenance et justificatifs de sortie licite. Les formalités culturelles et la déclaration douanière sont deux vérifications distinctes.',to==='monaco'?'Monaco is within the EU customs territory. Gather the invoice, provenance and lawful-export evidence; cultural-goods requirements are assessed separately from customs clearance.':'Gather the invoice, provenance and lawful-export evidence. Cultural-goods requirements and the customs declaration are separate checks.',['eu-import',...(to==='monaco'?['monaco-customs']:[])],1);
  if(!isEU(creation))add('icg','Identifier le document culturel requis','Identify the cultural-goods document required',age!==null&&age>200&&Number(r.valeur)>=18000?'L’âge et la valeur appellent un examen ICG : déclaration pour les catégories de la partie C ; licence pour les biens archéologiques ou éléments de monuments de la partie B de plus de 250 ans. Il reste à établir la catégorie et le pays de création ou découverte.':'La catégorie, la datation, la valeur et le pays de création ou découverte permettent de déterminer s’il faut une licence ou une déclaration ICG. Même sans formalité ICG, la sortie licite reste à documenter.',age!==null&&age>200&&Number(r.valeur)>=18000?'The age and value require an ICG assessment: an importer statement for Annex C categories; a licence for Annex B archaeological objects or monument elements over 250 years old. Category and country of creation or discovery still need evidence.':'Category, date, value and country of creation or discovery determine whether an ICG licence or importer statement is needed. Lawful export still matters where no ICG document is required.',['eu-thresholds'],1);
 }
 if(moving&&from==='france')add('export','Vérifier les autorisations de sortie','Check export and removal requirements','La catégorie, la datation, la valeur et la durée de présence en France déterminent les documents de sortie à examiner. Ajoutez la facture et les anciennes autorisations.','Category, date, value and time in France determine which removal and export documents need assessment. Add the invoice and any previous permits.',['fr-export'],1);
 if(!archive&&isCustomsUnion(from)&&(r.douaneDocument||r.arrivee==='importee'))add('customs','Lire le régime indiqué sur vos documents','Read the procedure recorded in your documents','Un carnet ATA, une admission temporaire ou un entrepôt peut imposer des conditions avant vente ou remise. Joignez le document ; une facture seule ne prouve pas la libre pratique.','An ATA carnet, temporary admission or customs warehousing may restrict sale or delivery. Add the document; a purchase invoice alone does not establish free circulation.',['eu-customs-procedures'],1);
 if(r.protege==='oui'||r.protege==='inconnu'||/ivoire|ivory|corail|coral|ecaille|tortoise/.test(norm(r.materiauxDetail)))add('cites','Préciser le composant protégé','Identify the protected material','Une photo rapprochée et un justificatif du matériau permettront d’examiner les permis CITES. L’ancienneté de l’objet ne suffit pas à l’en dispenser.','A close-up and material identification will help assess CITES documents. Age alone does not establish an exemption.',['cites'],1);
 if(/irak|iraq|syrie|syria/.test([from,creation,norm(r.origineCulturelle),norm(r.provenanceTexte)].join(' ')))add('origin','Reconstituer les sorties du pays d’origine','Reconstruct the export history','Cette provenance appelle un examen spécifique des restrictions et des dates de sortie. Conservez tous les anciens titres et documents de transport avant toute circulation ou vente.','This provenance requires specific checks on restrictions and export dates. Gather previous ownership and shipping records before sale or movement.',['restricted-origin'],0);
 if(sale){add('sale','Préparer une description qui engage justement','Get the sale description right','Nous rapprochons facture, certificat et catalogue pour reprendre la bonne attribution, les matériaux, la datation et les réserves dans les documents de vente. Les règles françaises ci-dessous ne sont applicables qu’après confirmation du droit de la vente.','We compare the invoice, certificate and catalogue to carry the supported attribution, materials, date and qualifications into the sale documents. The French rules below apply only where the sale is governed by them.',['fr-attribution','fr-sale'],3);
  add('parties','Identifier les parties, discrètement','Identify the parties, discreetly','Le mandat et les informations sur le vendeur et l’acheteur servent aux vérifications internes. La confidentialité côté acheteur n’efface pas les obligations d’identification ou de communication nécessaires. Le lieu d’établissement du professionnel détermine le régime de vigilance.','The mandate and party details support private checks. Buyer-facing privacy does not remove required identification or disclosure. The professional’s place of establishment determines the applicable due-diligence regime.',['fr-aml','mc-aml'],4);
  add('tax','Retenir la bonne fiscalité à partir de l’achat','Use the purchase history to establish tax treatment','Ajoutez la facture d’acquisition. Le régime dépend notamment du vendeur, du pays et du mode d’acquisition ; un objet de valeur n’est pas automatiquement une œuvre d’art au sens fiscal.','Add the acquisition invoice. Treatment depends on the seller, jurisdiction and acquisition route; not every valuable object qualifies as an artwork for tax purposes.',['fr-vat','fr-vat-margin'],4);
  if(r.acheteur==='particulier'&&r.mode==='distance')add('consumer','Préparer les informations de l’acheteur','Prepare the buyer’s terms','La vente à distance à un particulier appelle un examen de l’information préalable, de la rétractation et des garanties selon le droit applicable. Nous avons besoin des pays des parties et du mode exact de vente.','A distance sale to a private buyer requires assessment of pre-contract information, withdrawal and warranties under the applicable law. The parties’ countries and precise sales process are needed.',['fr-consumer'],3);
 }
 if(r.artisteNom){const t=artistTerm(r,year);add('rights','Distinguer la vente de l’œuvre et ses images','Separate ownership of the work from image rights',t?`La notice associée indique un décès en ${t.death}. Le repère ordinaire français est le 31 décembre ${t.ordinaryEndYear}. Il ne vaut pas autorisation : attribution, régimes particuliers, publication des images et éventuel droit de suite restent à examiner.`:'Nous recherchons les repères de l’artiste. Inutile de connaître vous-même la durée des droits : confirmez la bonne personne et joignez les éventuelles autorisations d’images.',t?`The linked record gives ${t.death} as the death year. The ordinary French term points to 31 December ${t.ordinaryEndYear}. This is not clearance: attribution, exceptions, image use and any resale royalty still need assessment.`:'We look up the artist’s biographical details. You do not need to calculate the copyright term: confirm the right person and add any image permissions.',['fr-copyright','fr-rights',...(sale?['fr-resale',...(from==='monaco'||to==='monaco'?['mc-resale']:[])]:[])],3);}
 const routes={
 "australie":{"export": ["au-export"], "import": [], "fr": "Vérifier le contrôle australien avant le départ", "en": "Check Australian export controls before departure", "detailFR": "La liste de contrôle et les éventuelles mesures de protection déterminent la procédure. Joignez facture, provenance et datation avant de fixer l’expédition.", "detailEN": "The Control List and any protective measures determine the procedure. Add the invoice, provenance and dating evidence before arranging shipment."},
 "japon":{"export": ["jp-export"], "import": [], "fr": "Vérifier la désignation patrimoniale japonaise", "en": "Check Japanese cultural-property designation", "detailFR": "Joignez photos, description et justificatifs de provenance. Pour l’art ancien, examinons le certificat de non-désignation auprès de l’Agence pour les affaires culturelles avant le départ.", "detailEN": "Add photographs, a description and provenance records. For antique art, assess the certificate of non-designation with the Agency for Cultural Affairs before departure."},
 "canada":{"export": ["ca-export"], "import": [], "fr": "Préparer le permis de sortie canadien", "en": "Prepare the Canadian export permit", "detailFR": "La catégorie, la datation, l’auteur et la valeur permettent de consulter la Liste de contrôle. Joignez facture et catalogue ; le permis doit être demandé par un résident canadien.", "detailEN": "Category, date, artist and value determine the Control List assessment. Add the invoice and catalogue; a Canadian resident must apply for the permit."},
 'royaume-uni':{export:['uk-export'],import:[],fr:'Distinguer Grande-Bretagne et Irlande du Nord',en:'Distinguish Great Britain from Northern Ireland',detailFR:'Confirmez la localisation exacte et joignez facture, datation et anciennes licences. Nous orientons la préparation vers Arts Council England avant expédition.',detailEN:'Confirm the precise location and add the invoice, dating evidence and previous licences. This establishes the route to Arts Council England before shipment.'},
 'suisse':{export:['ch-customs'],import:['ch-customs'],fr:'Préparer la déclaration culturelle suisse',en:'Prepare the Swiss cultural-property declaration',detailFR:'Réunissez facture, provenance, datation et dimensions, puis les anciens documents douaniers. Le dépôt en entrepôt appelle aussi une déclaration ; les restrictions et accords bilatéraux restent à examiner.',detailEN:'Gather the invoice, provenance, date, dimensions and previous customs records. Warehousing also requires a declaration; restrictions and bilateral agreements need separate assessment.'},
 'etats-unis':{export:[],import:['us-import'],fr:'Documenter l’entrée aux États-Unis',en:'Document the US import',detailFR:'Joignez facture, provenance et preuve de sortie du pays d’origine. Le classement tarifaire et les restrictions sur les biens culturels doivent être examinés séparément avec le représentant en douane.',detailEN:'Add the invoice, provenance and evidence of lawful export from the source country. Tariff classification and cultural-property restrictions need separate assessment with the customs broker.'},
 'hong kong':{export:['hk-declaration','hk-customs'],import:['hk-declaration','hk-customs'],fr:'Préparer les documents pour Hong Kong',en:'Prepare the Hong Kong documents',detailFR:'Joignez facture et documents de transport. Le port franc conserve des obligations de déclaration et des contrôles ; la sortie du pays précédent et les matériaux protégés restent à vérifier.',detailEN:'Add the invoice and shipping records. Free-port status does not remove declarations or controls; export from the previous country and regulated materials still need checking.'},
 'italie':{export:['it-export'],import:[],fr:'Identifier le bon parcours de sortie italien',en:'Identify the right Italian export procedure',detailFR:'La catégorie, la datation et les documents d’entrée permettent de choisir la démarche SUE et le bureau compétent. Joignez les anciens certificats avec la facture.',detailEN:'Category, date and entry records determine the SUE procedure and competent office. Add previous certificates with the invoice.'},
 'allemagne':{export:['de-export'],import:[],fr:'Vérifier la sortie selon le KGSG allemand',en:'Assess export under the German KGSG',detailFR:'Réunissez datation, valeur, provenance et éventuels documents de protection. Le parcours officiel permet d’identifier l’autorisation adaptée à la destination.',detailEN:'Gather dating evidence, value, provenance and any protection records. The official process identifies the permit for the destination.'}
 };
 if(moving){const a=routes[from],b=routes[to];if(a?.export.length)add('local-export-guided',a.fr,a.en,a.detailFR,a.detailEN,a.export,1);if(b?.import.length)add('local-import-guided',b.fr,b.en,b.detailFR,b.detailEN,b.import,1);}
 if(sale)add('professional-care','Conserver les vérifications utiles','Keep a record of the relevant checks','Provenance, pouvoir de vendre et description étayée : nous regroupons les éléments utiles au dossier professionnel. Le code déontologique applicable dépend de votre activité et de vos affiliations.','Provenance, authority to sell and a supported description belong in the professional record. The applicable professional code depends on your activity and affiliations.',['cinoa-ethics',...((from==='france'||to==='france')?['fr-auction-ethics']:[]),...((from==='suisse'||to==='suisse')?['ch-trade']:[]),...((from==='royaume-uni'||to==='royaume-uni')?['uk-aml']:[])],4);
 if(moving&&!['france','inde','monaco'].includes(from)&&!routes[from]?.export.length)add('local-export','Vérifier aussi le droit du pays de départ','Check the departure country’s rules too','Les formalités locales de sortie ne sont pas encore qualifiées pour ce pays dans ce socle. Une confirmation des douanes ou de l’autorité du patrimoine est nécessaire avant d’annoncer une circulation autorisée.','This source pack does not yet establish the departure country’s export requirements. Customs or the cultural-heritage authority must confirm them before movement can be treated as authorised.',[],2);
 if(moving&&!isCustomsUnion(to)&&!routes[to]?.import.length)add('local-import','Confirmer les conditions à destination','Confirm the destination requirements','Le régime d’importation de cette destination reste à documenter auprès des autorités locales. Les seuils européens ne permettent pas de le déduire.','The destination’s import requirements still need local official verification. EU thresholds cannot establish them.',[],2);
 if(moving&&from==='monaco')add('mc-exit','Vérifier la protection patrimoniale locale','Check local heritage protection','Avant la sortie, examinez un éventuel classement ou une mesure de protection monégasque. Le régime douanier ne résout pas à lui seul cette question.','Before removal, check for any Monegasque designation or protection. Customs treatment alone does not answer this question.',['mc-patrimoine'],2);
 return {version:'guide-4.1',reviewed:REVIEWED,route:moving?`${r.lieu} → ${r.dest}`:'',items:items.sort((a,b)=>a.priority-b.priority),documents:documentsFor(r,lang),coverage:'Socle thématique France, Monaco et UE ; modules limités Inde, Royaume-Uni, Suisse, États-Unis, Hong Kong, Italie, Allemagne, Canada, Japon et Australie. Codes professionnels distingués des lois. Droit des contrats, fiscalité, sanctions et objets spécialisés non exhaustifs. Autres pays : qualification locale requise. Sources révisées manuellement, aucune veille automatique active.'};
}
export function promptContext(r,message=''){
 const p=plan(r);const ids=new Set(p.items.flatMap(x=>x.sources.map(s=>s.id)));
 // Topic matching selects trusted texts; message text is never inserted into instructions.
 const topic=norm(message);
 const countryTopics=[[/suisse|switzerland/,['ch-customs','ch-trade']],[/royaume.uni|united kingdom|britain|london|londres/,['uk-export','uk-aml']],[/etats.unis|united states|new york/,['us-import']],[/hong kong/,['hk-customs','hk-declaration']],[/italie|italy/,['it-export']],[/allemagne|germany/,['de-export']],[/canada/,['ca-export']],[/japon|japan/,['jp-export']],[/australie|australia/,['au-export']]];
 for(const [pattern,refs] of countryTopics)if(pattern.test(topic))refs.forEach(id=>ids.add(id));
 if(/deontolog|ethic|cinoa|provenance/.test(topic))ids.add('cinoa-ethics');
 if(/encher|auction/.test(topic)&&norm(r.lieu)==='france')ids.add('fr-auction-ethics');
 if(/inde|india/.test(topic))['india-export','eu-import','eu-thresholds','monaco-customs'].forEach(id=>ids.add(id));
 if(/import|export|douan|custom|transport/.test(topic))['eu-import','eu-thresholds','fr-export','monaco-customs','eu-customs-procedures'].forEach(id=>ids.add(id));
 if(/artiste|artist|deces|death|droit|copyright|70/.test(topic))['fr-copyright','fr-rights','fr-resale','mc-resale'].forEach(id=>ids.add(id));
 if(/vente|sell|sale|contrat|contract|facture|invoice/.test(topic))['fr-attribution','fr-sale','fr-vat','fr-vat-margin','fr-consumer','fr-registry'].forEach(id=>ids.add(id));
 if(/ivoire|ivory|cites|coral|ecaille/.test(topic))ids.add('cites');
 if(/irak|iraq|syrie|syria/.test(topic))ids.add('restricted-origin');
 const selected=SOURCES.filter(s=>ids.has(s.id));
 const ageDays=Math.floor((Date.now()-Date.parse(REVIEWED+'T00:00:00Z'))/86400000);
 return {version:'guide-4.1',reviewed:REVIEWED,coverage:p.coverage,freshness:ageDays>30?'revalidation-required':'within-editorial-review-window',policy:'Sources préchargées et sélectionnées sans recherche réseau. Ni qualification définitive ni vérification de sanctions en temps réel. Si revalidation-required, ne pas présenter les textes comme fraîchement vérifiés. Le code professionnel ne devient pas une loi universelle. Aucun pays non couvert ne reçoit une autorisation par défaut.',sources:selected,nextDocuments:documentsFor(r)};
}
