/* ARTVELCHIV — curated legal guidance, not a legal-clearance engine.
 * Every source has a defined scope. No source updates or filings are implied.
 * Shared by the interface and both language-model providers. No private data here.
 */
export const REVIEWED='2026-10-04';
const source=(id,title,url,scope,rule)=>({id,title,url,scope,rule,reviewed:REVIEWED});
export const SOURCES=[
 source('eu-customs-procedures','UE · régimes particuliers et carnet ATA','https://www.douane.gouv.fr/dossier/les-regimes-particuliers','Biens non Union sous régime particulier','L’admission temporaire et l’entrepôt permettent certains usages ou stockages en suspension de droits et taxes. Les conditions de vente, mise en libre pratique, réexportation et délais dépendent du régime et de l’autorisation. Lire la déclaration et consulter le représentant en douane avant livraison.'),
 source('eu-import','UE · règlement 2019/880 et mise en œuvre 2021/1079','https://www.douane.gouv.fr/demarche/importer-des-biens-culturels','Entrée dans le territoire douanier de l’Union de biens créés ou découverts hors UE','L’introduction de biens culturels illicitement exportés est interdite. Depuis le 28 juin 2025, les parties B et C imposent respectivement une licence ou une déclaration ICG. Les exceptions et le pays dont il faut prouver la sortie licite nécessitent l’historique du bien. L’article L111-8 du code du patrimoine a ses propres conditions cumulatives ; pas de permis d’origine universel.'),
 source('eu-thresholds','UE · catégories et seuils des formalités ICG','https://www.douane.gouv.fr/sites/default/files/2023-05/17/biens-culturels-reglementation-europeenne-applicable-a-l-introduction-et-a-l-importation.pdf','Biens entrant dans les catégories précises de l’annexe 2019/880','Partie B : biens archéologiques et éléments de monuments démembrés de plus de 250 ans, sans seuil de valeur. Partie C : catégories visées de plus de 200 ans, valeur d’au moins 18 000 € par objet. Âge, catégorie et valeur sont cumulatifs en C. Une sculpture ancienne n’est pas nécessairement archéologique. Ne jamais déduire une exemption générale de l’absence de formalité ICG.'),
 source('monaco-customs','Monaco · territoire douanier (CDU, article 4)','https://www.douane.gouv.fr/sites/default/files/2024-03/01/Manuel-transit-preuve-du-statut-p77-a-183.pdf','Circulation vers ou depuis Monaco','Monaco appartient au territoire douanier de l’Union en vertu de la convention douanière franco-monégasque. Ce n’est pas un État membre de l’UE. Cette inclusion ne rend pas automatiquement applicables toutes les règles civiles, fiscales, de consommation ou de propriété intellectuelle françaises.'),
 source('india-export','Inde · Antiquities and Art Treasures Act 1972, sections 2–3','https://www.wipo.int/wipolex/en/legislation/details/14946','Sortie physique d’Inde','Les antiquités visées comprennent notamment les objets ayant au moins 100 ans et certains manuscrits ou documents ayant au moins 75 ans. Les art treasures sont désignés par notification. Leur exportation est réservée au gouvernement central ou à une autorité/agence autorisée : ce n’est pas un permis ordinaire ouvert à tout vendeur. Faire confirmer la catégorie par l’ASI et les douanes avant expédition. Une origine stylistique indienne ne prouve pas une sortie actuelle d’Inde.'),
 source('fr-export','France · exportation des biens culturels','https://www.douane.gouv.fr/demarche/exporter-des-biens-culturels','Sortie de France ou du territoire douanier de l’Union','Distinguer certificat national / autorisation de sortie temporaire et licence européenne d’exportation (règlement 116/2009). Les seuils varient par catégorie, ancienneté et valeur ; ne pas réutiliser les seuils ICG d’importation. Les trésors nationaux relèvent d’une sortie temporaire. Examiner la durée de présence en France et le régime temporaire avant de conclure.'),
 source('cites','Espèces protégées · CITES et règlement 338/97','https://www.douane.gouv.fr/demarche/importer-des-specimens-cites','Objets comprenant des espèces animales ou végétales réglementées','Les documents dépendent de l’espèce, de l’annexe, du trajet, de la date et du régime. L’ancienneté ne dispense pas automatiquement de permis ou de certificat. Identifier les composants ; examiner les permis d’exportation/réexportation et d’importation avant transport. En France, service CITES compétent, généralement DREAL/DRIEAT/DEAL.'),
 source('fr-attribution','France · décret 81-255, articles 1 à 8','https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000684875/','Descriptions et vente d’œuvres ou objets de collection en France','Le nom de l’artiste, la datation et les expressions d’attribution ont des effets distincts. « Attribué à » n’équivaut pas à une œuvre garantie de la main de l’artiste ; « d’après » doit rester distinct. Décrire les reproductions et les parties postérieures. Rapprocher les affirmations du catalogue, du certificat et de la facture avant de rédiger le contrat.'),
 source('fr-copyright','France · CPI L123-1 (durée des droits patrimoniaux)','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006278937','Durée ordinaire de protection en France','La règle ordinaire couvre la vie de l’auteur puis l’année du décès et les 70 années suivantes. Le repère de fin est le 31 décembre de l’année du décès + 70, sous réserve des régimes spéciaux et internationaux. L’âge de l’objet n’est pas la date de décès de l’artiste. Une notice biographique ne vaut pas autorisation d’utilisation.'),
 source('fr-rights','France · CPI L111-3 et L121-1','https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006069414/LEGISCTA000006133323/','Propriété matérielle, reproduction et droit moral','Acheter l’objet ne transfère pas automatiquement les droits d’auteur. Le droit moral reste protégé en France indépendamment de l’expiration des droits patrimoniaux. Examiner séparément vente matérielle, publication des images et autorisations ; ne pas appeler une œuvre « libre de tous droits » sur la seule base d’une date.'),
 source('fr-resale','France · CPI L122-8, droit de suite','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033688066','Reventes d’originaux avec intervention d’un professionnel en France','Le droit de suite dépend notamment de l’originalité/édition, de l’auteur et de ses ayants droit, de la revente, du professionnel et des conditions territoriales et financières. Une date de décès ne suffit pas à qualifier toute la vente. Identifier le bénéficiaire et l’organisme compétent avant de calculer ou d’attribuer des frais.'),
 source('mc-resale','Monaco · loi 1.526 du 1er juillet 2022','https://journaldemonaco.gouv.mc/Journaux/2022/Journal-8599/Loi-n-1.526-du-1er-juillet-2022-relative-au-droit-de-suite','Droit de suite monégasque','Monaco dispose d’un régime propre de droit de suite. Ne pas appliquer automatiquement les modalités françaises ; vérifier les conditions et le texte d’application monégasque pour la transaction.'),
 source('fr-aml','France · vigilance des marchands d’art et d’antiquités','https://www.douane.gouv.fr/fiche/marchands-dart-et-dantiquites','Professionnels assujettis en France','Le secteur est assujetti à la lutte contre le blanchiment pour les transactions ou séries liées d’au moins 10 000 €. Identifier client, représentation et bénéficiaire effectif, apprécier le risque et conserver les justificatifs selon le cadre applicable. Ne pas conclure qu’un montant inférieur exclut tout contrôle. Les vérifications internes ne sont pas des annexes publiques du dossier acheteur.'),
 source('mc-aml','Monaco · loi 1.362 et ordonnance 2.318','https://legimonaco.mc/tnc/loi/2009/08-03-1.362','Professionnels assujettis à Monaco','Le régime monégasque de vigilance doit être examiné selon la catégorie de professionnel et l’opération. Ne pas transposer les seuils français ni confondre art et autres objets de valeur. Vérifier la loi et son ordonnance d’application auprès du dispositif monégasque compétent avant de conclure.'),
 source('mc-patrimoine','Monaco · loi 1.446 sur le patrimoine national','https://legimonaco.mc/tnc/loi/2017/06-12-1.446/','Protection patrimoniale à Monaco','Examiner la protection patrimoniale locale et les éventuelles restrictions avant une sortie. L’union douanière n’écarte pas les règles monégasques du patrimoine. Ce repère ne permet pas, seul, de calculer les autorisations requises.'),
 source('fr-vat','France · BOI-TVA-SECT-90-40, version du 14 mai 2025','https://bofip.impots.gouv.fr/bofip/1285-PGP.html/identifiant=BOI-TVA-SECT-90-40-20250514','TVA française des œuvres d’art, objets de collection et antiquités fiscalement qualifiés','Depuis le 1er janvier 2025, les livraisons qualifiées relèvent du taux réduit de 5,5 %, sauf application du régime de la marge. Le régime dépend de l’acquisition, du vendeur et de l’opération. Ne pas présumer la TVA ni étendre le taux à tout objet de valeur. Importation, livraison et marge doivent rester distinctes.'),
 source('fr-vat-margin','France · BOI-TVA-SECT-90-20-20','https://bofip.impots.gouv.fr/bofip/13268-PGP.html/identifiant=BOI-TVA-SECT-90-20-20-20250514','Assujettis-revendeurs et régime de la marge','Examiner la facture d’achat et la qualité du cédant avant de proposer le régime de la marge. Ne pas cumuler automatiquement marge et taux réduit de 5,5 %. Une facture ne prouve pas à elle seule l’acquittement de TVA d’importation.'),
 source('fr-consumer','France · Code de la consommation, L221-18','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032226842','Contrats à distance ou hors établissement avec un consommateur lorsque le droit français s’applique','Le délai de rétractation de principe est de 14 jours, sous réserve du champ du texte et des exceptions. Les ventes aux enchères publiques et les ventes en ligne ne sont pas assimilables sans examen. Prévoir informations précontractuelles, garanties et modalités de retour selon le contrat ; ne pas supprimer des droits impératifs.'),
 source('fr-registry','France · Code pénal, article 321-7','https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000023717783','Professionnels concernés par le registre des objets mobiliers','Certaines activités de vente de biens mobiliers usagés ou acquis hors fabrication/commerce imposent un registre. Conserver identification, provenance et vendeur. Une archive Artvelchiv n’est pas automatiquement un registre réglementaire conforme.'),
 source('fr-sale','France · Code civil, vente et garanties','https://www.legifrance.gouv.fr/codes/id/LEGITEXT000006070721','Vente soumise au droit français','Examiner information et consentement, délivrance, garantie d’éviction (1626) et vices cachés (1641). Définir objet/attribution, parties et mandat, prix et fiscalité, paiement, livraison, assurance et réserves. Les garanties impératives et règles de conflit ne peuvent être écartées par une simple clause modèle.'),
 source('restricted-origin','UE · biens culturels irakiens et syriens','https://www.douane.gouv.fr/demarche/importer-des-biens-culturels','Provenance irakienne ou syrienne','Des restrictions spécifiques s’ajoutent au régime général. Reconstituer les dates et circonstances de sortie et consulter les règlements 1210/2003 (Irak) et 36/2012 modifié notamment par 1332/2013 (Syrie). Ne pas conclure à une circulation autorisée sans examen des justificatifs et exceptions.')
];
const get=id=>SOURCES.find(s=>s.id===id);
const norm=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const EU=['france','allemagne','autriche','belgique','bulgarie','chypre','croatie','danemark','espagne','estonie','finlande','grece','hongrie','irlande','italie','lettonie','lituanie','luxembourg','malte','pays-bas','pologne','portugal','republique tcheque','tchequie','roumanie','slovaquie','slovenie','suede'];
export const isEU=x=>EU.includes(norm(x));
export const isCustomsUnion=x=>isEU(x)||norm(x)==='monaco';
const tr=(lang,fr,en)=>lang==='en'?en:fr;
export function artistTerm(record,year=new Date().getFullYear()){
 const values=[...new Set((record.artistReference?.death||[]).map(String).filter(x=>/^\d{4}$/.test(x)).map(Number))];
 if(values.length!==1||values[0]>year||values[0]<1)return null;
 const death=values[0];return {death,ordinaryEndYear:death+70,ordinaryExpired:year>death+70,scope:'France',clearance:false};
}
export function documentsFor(r,lang='fr'){
 const out=[{id:'acquisition',title:tr(lang,'Facture ou bordereau d’achat','Purchase invoice or auction receipt'),why:tr(lang,'Pour retrouver l’acquisition, le vendeur et la description d’origine.','To recover the acquisition details, seller and original description.')},{id:'identity',title:tr(lang,'Certificat, expertise ou ancien catalogue','Certificate, expert opinion or previous catalogue'),why:tr(lang,'Pour préciser l’artiste, la date et les matériaux.','To establish the recorded attribution, date and materials.')}];
 if(r.lieu&&r.dest&&r.lieu!==r.dest||r.arrivee==='importee'||r.douaneDocument)out.push({id:'transport',title:tr(lang,'Documents de transport ou de douane','Shipping or customs documents'),why:tr(lang,'Pour lire le trajet, le régime déclaré et les éventuelles échéances.','To identify the route, declared procedure and any deadlines.')});
 if(r.role==='mandataire')out.push({id:'mandate',title:tr(lang,'Mandat du propriétaire','Owner’s mandate'),why:tr(lang,'Pour préciser qui peut vendre et signer.','To establish authority to sell and sign.')});
 if(r.protege==='oui'||r.protege==='inconnu'||/ivoire|ivory|corail|coral|ecaille|tortoise/i.test(norm(r.materiauxDetail)))out.push({id:'materials',title:tr(lang,'Justificatif des matériaux','Material identification or permit'),why:tr(lang,'Pour examiner les composants réglementés.','To assess regulated components.')});
 return out;
}
export function plan(r={},lang='fr',year=new Date().getFullYear()){
 const items=[];const add=(id,fr,en,detailFR,detailEN,refs,priority=2)=>items.push({id,title:tr(lang,fr,en),detail:tr(lang,detailFR,detailEN),sources:refs.map(get).filter(Boolean),priority,status:'to-review'});
 const from=norm(r.lieu),to=norm(r.dest),creation=norm(r.creation),sale=['vente','achat'].includes(r.operation),archive=r.operation==='archiver';
 const moving=!!(from&&to&&from!==to&&!archive),incoming=moving&&!isCustomsUnion(from)&&isCustomsUnion(to),age=Number.isFinite(Number(r.annee))&&r.annee!==''&&r.annee!=null?year-Number(r.annee):null;
 if(moving&&from==='inde')add('india','Vérifier la sortie d’Inde avant le transport','Check export eligibility before shipping from India',age!==null&&age>=100?'Cette datation place l’objet dans une tranche d’âge susceptible de relever de l’interdiction d’exportation des antiquités. Demandez une confirmation de classement à l’ASI avec la facture, les photos et la datation ; une licence ordinaire ne suffit pas.':'La sortie dépend de l’âge, de la catégorie et d’un éventuel classement. Joignez facture, photos et datation : il faut d’abord écarter les restrictions indiennes, avant d’organiser le transport.',age!==null&&age>=100?'This date puts the object within an age range potentially covered by India’s antiquities export prohibition. Ask the ASI to confirm its classification using the invoice, photographs and dating evidence; an ordinary export permit is not sufficient.':'Export depends on age, category and any protected designation. Supply the invoice, photographs and dating evidence so Indian restrictions can be checked before shipping.',['india-export'],0);
 if(incoming){
  add('import','Préparer l’entrée à destination','Prepare the import at destination',to==='monaco'?'Monaco fait partie du territoire douanier de l’Union. Réunissez facture, provenance et justificatifs de sortie licite ; nous distinguons ensuite les documents culturels du dédouanement.':'Réunissez facture, provenance et justificatifs de sortie licite. Les formalités culturelles et la déclaration douanière sont deux vérifications distinctes.',to==='monaco'?'Monaco is within the EU customs territory. Gather the invoice, provenance and lawful-export evidence; cultural-goods requirements are assessed separately from customs clearance.':'Gather the invoice, provenance and lawful-export evidence. Cultural-goods requirements and the customs declaration are separate checks.',['eu-import',...(to==='monaco'?['monaco-customs']:[])],1);
  if(!isEU(creation))add('icg','Identifier le document culturel requis','Identify the cultural-goods document required',age!==null&&age>200&&Number(r.valeur)>=18000?'L’âge et la valeur appellent un examen ICG : déclaration pour les catégories de la partie C ; licence pour les biens archéologiques ou éléments de monuments de la partie B de plus de 250 ans. Il reste à établir la catégorie et le pays de création ou découverte.':'La catégorie, la datation, la valeur et le pays de création ou découverte permettent de déterminer s’il faut une licence ou une déclaration ICG. Même sans formalité ICG, la sortie licite reste à documenter.',age!==null&&age>200&&Number(r.valeur)>=18000?'The age and value require an ICG assessment: an importer statement for Annex C categories; a licence for Annex B archaeological objects or monument elements over 250 years old. Category and country of creation or discovery still need evidence.':'Category, date, value and country of creation or discovery determine whether an ICG licence or importer statement is needed. Lawful export still matters where no ICG document is required.',['eu-thresholds'],1);
 }
 if(moving&&from==='france')add('export','Vérifier les autorisations de sortie','Check export and removal requirements','La catégorie, la datation, la valeur et la durée de présence en France déterminent les documents de sortie à examiner. Ajoutez la facture et les anciennes autorisations.','Category, date, value and time in France determine which removal and export documents need assessment. Add the invoice and any previous permits.',['fr-export'],1);
 if(!archive&&isCustomsUnion(from)&&(r.douaneDocument||r.arrivee==='importee'))add('customs','Lire le régime indiqué sur vos documents','Read the procedure recorded in your documents','Un carnet ATA, une admission temporaire ou un entrepôt peut imposer des conditions avant vente ou remise. Joignez le document ; une facture seule ne prouve pas la libre pratique.','An ATA carnet, temporary admission or customs warehousing may restrict sale or delivery. Add the document; a purchase invoice alone does not establish free circulation.',['eu-customs-procedures'],1);
 if(r.protege==='oui'||r.protege==='inconnu'||/ivoire|ivory|corail|coral|ecaille|tortoise/.test(norm(r.materiauxDetail)))add('cites','Préciser le composant protégé','Identify the protected material','Une photo rapprochée et un justificatif du matériau permettront d’examiner les permis CITES. L’ancienneté de l’objet ne suffit pas à l’en dispenser.','A close-up and material identification will help assess CITES documents. Age alone does not establish an exemption.',['cites'],1);
 if(/irak|iraq|syrie|syria/.test([from,creation,norm(r.origineCulturelle),norm(r.provenanceTexte)].join(' ')))add('origin','Reconstituer les sorties du pays d’origine','Reconstruct the export history','Cette provenance appelle un examen spécifique des restrictions et des dates de sortie. Conservez tous les anciens titres et documents de transport avant toute circulation ou vente.','This provenance requires specific checks on restrictions and export dates. Gather previous ownership and shipping records before sale or movement.',['restricted-origin'],0);
 if(sale){add('sale','Préparer une description qui engage justement','Get the sale description right','Nous rapprochons facture, certificat et catalogue pour reprendre la bonne attribution, les matériaux, la datation et les réserves dans les documents de vente. Les règles françaises ci-dessous ne sont applicables qu’après confirmation du droit de la vente.','We compare the invoice, certificate and catalogue to carry the supported attribution, materials, date and qualifications into the sale documents. The French rules below apply only where the sale is governed by them.',['fr-attribution','fr-sale'],3);
  add('parties','Identifier les parties, discrètement','Identify the parties, discreetly','Le mandat et les informations sur le vendeur et l’acheteur servent aux vérifications internes. La confidentialité côté acheteur n’efface pas les obligations d’identification ou de communication nécessaires. Le lieu d’établissement du professionnel détermine le régime de vigilance.','The mandate and party details support private checks. Buyer-facing privacy does not remove required identification or disclosure. The professional’s place of establishment determines the applicable due-diligence regime.',['fr-aml','mc-aml'],4);
  add('tax','Retenir la bonne fiscalité à partir de l’achat','Use the purchase history to establish tax treatment','Ajoutez la facture d’acquisition. Le régime dépend notamment du vendeur, du pays et du mode d’acquisition ; un objet de valeur n’est pas automatiquement une œuvre d’art au sens fiscal.','Add the acquisition invoice. Treatment depends on the seller, jurisdiction and acquisition route; not every valuable object qualifies as an artwork for tax purposes.',['fr-vat','fr-vat-margin'],4);
  if(r.acheteur==='particulier'&&r.mode==='distance')add('consumer','Préparer les informations de l’acheteur','Prepare the buyer’s terms','La vente à distance à un particulier appelle un examen de l’information préalable, de la rétractation et des garanties selon le droit applicable. Nous avons besoin des pays des parties et du mode exact de vente.','A distance sale to a private buyer requires assessment of pre-contract information, withdrawal and warranties under the applicable law. The parties’ countries and precise sales process are needed.',['fr-consumer'],3);
 }
 if(r.artisteNom){const t=artistTerm(r,year);add('rights','Distinguer la vente de l’œuvre et ses images','Separate ownership of the work from image rights',t?`La notice associée indique un décès en ${t.death}. Le repère ordinaire français est le 31 décembre ${t.ordinaryEndYear}. Il ne vaut pas autorisation : attribution, régimes particuliers, publication des images et éventuel droit de suite restent à examiner.`:'Nous recherchons les repères de l’artiste. Inutile de connaître vous-même la durée des droits : confirmez la bonne personne et joignez les éventuelles autorisations d’images.',t?`The linked record gives ${t.death} as the death year. The ordinary French term points to 31 December ${t.ordinaryEndYear}. This is not clearance: attribution, exceptions, image use and any resale royalty still need assessment.`:'We look up the artist’s biographical details. You do not need to calculate the copyright term: confirm the right person and add any image permissions.',['fr-copyright','fr-rights',...(sale?['fr-resale',...(from==='monaco'||to==='monaco'?['mc-resale']:[])]:[])],3);}
 if(moving&&!['france','inde','monaco'].includes(from))add('local-export','Vérifier aussi le droit du pays de départ','Check the departure country’s rules too','Les formalités locales de sortie ne sont pas encore qualifiées pour ce pays dans ce socle. Une confirmation des douanes ou de l’autorité du patrimoine est nécessaire avant d’annoncer une circulation autorisée.','This source pack does not yet establish the departure country’s export requirements. Customs or the cultural-heritage authority must confirm them before movement can be treated as authorised.',[],2);
 if(moving&&!isCustomsUnion(to))add('local-import','Confirmer les conditions à destination','Confirm the destination requirements','Le régime d’importation de cette destination reste à documenter auprès des autorités locales. Les seuils européens ne permettent pas de le déduire.','The destination’s import requirements still need local official verification. EU thresholds cannot establish them.',[],2);
 if(moving&&from==='monaco')add('mc-exit','Vérifier la protection patrimoniale locale','Check local heritage protection','Avant la sortie, examinez un éventuel classement ou une mesure de protection monégasque. Le régime douanier ne résout pas à lui seul cette question.','Before removal, check for any Monegasque designation or protection. Customs treatment alone does not answer this question.',['mc-patrimoine'],2);
 return {version:'guide-4.0',reviewed:REVIEWED,route:moving?`${r.lieu} → ${r.dest}`:'',items:items.sort((a,b)=>a.priority-b.priority),documents:documentsFor(r,lang),coverage:'France, Monaco et UE : socle thématique ; Inde : sortie des antiquités. Autres pays et objets spécialisés : vérification locale nécessaire. Aucune exhaustivité mondiale ni mise à jour automatique.'};
}
export function promptContext(r,message=''){
 const ids=new Set(plan(r).items.flatMap(x=>x.sources.map(s=>s.id)));
 // Topic matching selects trusted texts; message text is never inserted into instructions.
 const topic=norm(message);
 if(/inde|india/.test(topic))['india-export','eu-import','eu-thresholds','monaco-customs'].forEach(id=>ids.add(id));
 if(/import|export|douan|custom|transport/.test(topic))['eu-import','eu-thresholds','fr-export','monaco-customs','eu-customs-procedures'].forEach(id=>ids.add(id));
 if(/artiste|artist|deces|death|droit|copyright|70/.test(topic))['fr-copyright','fr-rights','fr-resale','mc-resale'].forEach(id=>ids.add(id));
 if(/vente|sell|sale|contrat|contract|facture|invoice/.test(topic))['fr-attribution','fr-sale','fr-vat','fr-vat-margin','fr-consumer','fr-registry'].forEach(id=>ids.add(id));
 if(/ivoire|ivory|cites|coral|ecaille/.test(topic))ids.add('cites');
 if(/irak|iraq|syrie|syria/.test(topic))ids.add('restricted-origin');
 return {reviewed:REVIEWED,coverage:plan(r).coverage,sources:SOURCES.filter(s=>ids.has(s.id)),nextDocuments:documentsFor(r)};
}
